import { Cliente, Conductor, Vehiculo, Orden, Guia, Factura, Usuario } from './store';
import { v4 as uuidv4 } from 'uuid';

export const EMISOR = {
  ruc: '20505000999',
  razonSocial: 'TRANSPORTES DEMO S.A.C.',
  nombreComercial: 'Demo Transportes',
  direccion: 'Av. Las Flores 456, Piso 3',
  ubigeo: '150131',
  telefono: '(01) 2345-6789',
  email: 'contacto@demo.pe',
};

const createCliente = (data: Partial<Cliente>): Cliente => ({
  id: uuidv4(),
  tipoDoc: 6,
  numeroDoc: '20505000999',
  razonSocial: 'CLIENTE DEMO',
  nombreComercial: 'Demo Client',
  dirección: 'Av. Principal 123',
  ubigeo: '150131',
  telefono: '01-2345678',
  email: 'cliente@demo.com',
  activo: true,
  createdAt: new Date(),
  ...data,
});

const createConductor = (data: Partial<Conductor>): Conductor => ({
  id: uuidv4(),
  dni: '12345678',
  nombres: 'Juan',
  apellidos: 'García',
  licencia: 'B-001234',
  categoriaLicencia: 'A-IIIa',
  vencimientoLicencia: new Date('2026-12-31'),
  activo: true,
  createdAt: new Date(),
  ...data,
});

const createVehiculo = (data: Partial<Vehiculo>): Vehiculo => ({
  id: uuidv4(),
  placa: 'ABC-123',
  configuracion: 'C2',
  anio: 2020,
  capacidadKg: 5000,
  vencimientoSOAT: new Date('2026-12-31'),
  vencimientoRevision: new Date('2026-06-30'),
  activo: true,
  createdAt: new Date(),
  ...data,
});

const createOrden = (data: Partial<Orden>): Orden => ({
  id: uuidv4(),
  numero: 'ORD-001',
  clienteId: uuidv4(),
  conductorId: uuidv4(),
  vehiculoId: uuidv4(),
  modalidadTransporte: '01',
  origen: { direccion: 'Lima', ubigeo: '150131' },
  destino: { direccion: 'Arequipa', ubigeo: '080131' },
  fechaInicioTraslado: new Date(),
  pesoTotal: 1500,
  bultos: 10,
  descripcionMercancia: 'Textiles',
  flete: 1000,
  igv: 180,
  total: 1180,
  estado: 'confirmada',
  createdAt: new Date(),
  updatedAt: new Date(),
  ...data,
});

const createFacturaItem = (data: Partial<any> = {}) => ({
  id: uuidv4(),
  descripcion: 'Servicio de Transporte',
  cantidad: 1,
  unitario: 1000,
  subtotal: 1000,
  ...data,
});

export const seedClientes: Cliente[] = [
  createCliente({ numeroDoc: '20505000999', razonSocial: 'TRANSPORTES DEMO S.A.C.' }),
  createCliente({ numeroDoc: '10123456789', tipoDoc: 1, razonSocial: 'Juan Pérez', nombreComercial: 'JP Servicios' }),
  createCliente({ numeroDoc: '20987654321', razonSocial: 'LOGÍSTICA PERUANA S.A.' }),
  createCliente({ numeroDoc: '10456789012', tipoDoc: 1, razonSocial: 'María López', nombreComercial: 'ML Distribución' }),
  createCliente({ numeroDoc: '20111111111', razonSocial: 'COMERCIAL ANDINA S.A.C.' }),
  createCliente({ numeroDoc: '10555555555', tipoDoc: 1, razonSocial: 'Carlos García', nombreComercial: 'CG Express' }),
  createCliente({ numeroDoc: '20222222222', razonSocial: 'TRANSPORTE NACIONAL E.I.R.L.' }),
  createCliente({ numeroDoc: '10777777777', tipoDoc: 1, razonSocial: 'Ana Rodríguez', nombreComercial: 'AR Logística' }),
];

export const seedConductores: Conductor[] = [
  createConductor({ dni: '12345678', nombres: 'Juan', apellidos: 'García', licencia: 'B-001234' }),
  createConductor({ dni: '23456789', nombres: 'Pedro', apellidos: 'López', licencia: 'B-002345', categoriaLicencia: 'A-IIIb' }),
  createConductor({ dni: '34567890', nombres: 'Carlos', apellidos: 'Rodríguez', licencia: 'B-003456', categoriaLicencia: 'A-II' }),
  createConductor({ dni: '45678901', nombres: 'Miguel', apellidos: 'Sánchez', licencia: 'B-004567' }),
  createConductor({ dni: '56789012', nombres: 'José', apellidos: 'Martínez', licencia: 'B-005678', categoriaLicencia: 'B-II' }),
  createConductor({ dni: '67890123', nombres: 'Luis', apellidos: 'Fernández', licencia: 'B-006789', categoriaLicencia: 'A-IIIa' }),
];

export const seedVehiculos: Vehiculo[] = [
  createVehiculo({ placa: 'ABC-123', configuracion: 'C2' }),
  createVehiculo({ placa: 'DEF-456', configuracion: 'C3', capacidadKg: 10000 }),
  createVehiculo({ placa: 'GHI-789', configuracion: 'C2', capacidadKg: 5000 }),
  createVehiculo({ placa: 'JKL-012', configuracion: 'T2S2', capacidadKg: 20000 }),
  createVehiculo({ placa: 'MNO-345', configuracion: 'T2S3', capacidadKg: 25000 }),
  createVehiculo({ placa: 'PQR-678', configuracion: 'C3', capacidadKg: 12000 }),
];

export const seedOrdenes: Orden[] = [
  createOrden({ numero: 'ORD-001', estado: 'borrador' }),
  createOrden({ numero: 'ORD-002', estado: 'confirmada', pesoTotal: 2000, flete: 1500, igv: 270, total: 1770 }),
  createOrden({ numero: 'ORD-003', estado: 'en_ruta', pesoTotal: 1200, flete: 800, igv: 144, total: 944 }),
  createOrden({ numero: 'ORD-004', estado: 'entregada', pesoTotal: 3000, flete: 2000, igv: 360, total: 2360 }),
  createOrden({ numero: 'ORD-005', estado: 'facturada', pesoTotal: 1800, flete: 1200, igv: 216, total: 1416 }),
  createOrden({ numero: 'ORD-006', estado: 'confirmada', pesoTotal: 2500, flete: 1800, igv: 324, total: 2124 }),
  createOrden({ numero: 'ORD-007', estado: 'en_ruta', pesoTotal: 1500, flete: 1000, igv: 180, total: 1180 }),
  createOrden({ numero: 'ORD-008', estado: 'entregada', pesoTotal: 2200, flete: 1600, igv: 288, total: 1888 }),
  createOrden({ numero: 'ORD-009', estado: 'facturada', pesoTotal: 1000, flete: 700, igv: 126, total: 826 }),
  createOrden({ numero: 'ORD-010', estado: 'borrador', pesoTotal: 3500, flete: 2500, igv: 450, total: 2950 }),
  createOrden({ numero: 'ORD-011', estado: 'confirmada', pesoTotal: 1300, flete: 900, igv: 162, total: 1062 }),
  createOrden({ numero: 'ORD-012', estado: 'en_ruta', pesoTotal: 2800, flete: 2000, igv: 360, total: 2360 }),
];

export const seedGuias: Guia[] = [
  {
    id: uuidv4(),
    numero: 'GR-001',
    ordenId: seedOrdenes[0].id,
    remitente: { razonSocial: EMISOR.razonSocial, numeroDoc: EMISOR.ruc },
    destinatario: { razonSocial: seedClientes[0].razonSocial, numeroDoc: seedClientes[0].numeroDoc },
    transportista: { razonSocial: EMISOR.razonSocial, ruc: EMISOR.ruc },
    conductor: { nombres: `${seedConductores[0].nombres} ${seedConductores[0].apellidos}`, dni: seedConductores[0].dni },
    vehiculo: { placa: seedVehiculos[0].placa },
    hash: 'abc123hash001',
    xml: '<GuiaRemision></GuiaRemision>',
    estado: 'emitida',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'GR-002',
    ordenId: seedOrdenes[1].id,
    remitente: { razonSocial: EMISOR.razonSocial, numeroDoc: EMISOR.ruc },
    destinatario: { razonSocial: seedClientes[1].razonSocial, numeroDoc: seedClientes[1].numeroDoc },
    transportista: { razonSocial: EMISOR.razonSocial, ruc: EMISOR.ruc },
    conductor: { nombres: `${seedConductores[1].nombres} ${seedConductores[1].apellidos}`, dni: seedConductores[1].dni },
    vehiculo: { placa: seedVehiculos[1].placa },
    hash: 'abc123hash002',
    xml: '<GuiaRemision></GuiaRemision>',
    estado: 'aceptada',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'GR-003',
    ordenId: seedOrdenes[2].id,
    remitente: { razonSocial: EMISOR.razonSocial, numeroDoc: EMISOR.ruc },
    destinatario: { razonSocial: seedClientes[2].razonSocial, numeroDoc: seedClientes[2].numeroDoc },
    transportista: { razonSocial: EMISOR.razonSocial, ruc: EMISOR.ruc },
    conductor: { nombres: `${seedConductores[2].nombres} ${seedConductores[2].apellidos}`, dni: seedConductores[2].dni },
    vehiculo: { placa: seedVehiculos[2].placa },
    hash: 'abc123hash003',
    xml: '<GuiaRemision></GuiaRemision>',
    estado: 'rechazada',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'GR-004',
    ordenId: seedOrdenes[3].id,
    remitente: { razonSocial: EMISOR.razonSocial, numeroDoc: EMISOR.ruc },
    destinatario: { razonSocial: seedClientes[3].razonSocial, numeroDoc: seedClientes[3].numeroDoc },
    transportista: { razonSocial: EMISOR.razonSocial, ruc: EMISOR.ruc },
    conductor: { nombres: `${seedConductores[3].nombres} ${seedConductores[3].apellidos}`, dni: seedConductores[3].dni },
    vehiculo: { placa: seedVehiculos[3].placa },
    hash: 'abc123hash004',
    xml: '<GuiaRemision></GuiaRemision>',
    estado: 'emitida',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'GR-005',
    ordenId: seedOrdenes[4].id,
    remitente: { razonSocial: EMISOR.razonSocial, numeroDoc: EMISOR.ruc },
    destinatario: { razonSocial: seedClientes[4].razonSocial, numeroDoc: seedClientes[4].numeroDoc },
    transportista: { razonSocial: EMISOR.razonSocial, ruc: EMISOR.ruc },
    conductor: { nombres: `${seedConductores[4].nombres} ${seedConductores[4].apellidos}`, dni: seedConductores[4].dni },
    vehiculo: { placa: seedVehiculos[4].placa },
    hash: 'abc123hash005',
    xml: '<GuiaRemision></GuiaRemision>',
    estado: 'aceptada',
    createdAt: new Date(),
  },
];

export const seedFacturas: Factura[] = [
  {
    id: uuidv4(),
    numero: 'F-001',
    ordenId: seedOrdenes[0].id,
    clienteId: seedClientes[0].id,
    clienteRazonSocial: seedClientes[0].razonSocial,
    clienteNumeroDoc: seedClientes[0].numeroDoc,
    items: [createFacturaItem({ unitario: 1000, subtotal: 1000 })],
    subtotal: 1000,
    igv: 180,
    detraccion: 40,
    total: 1140,
    xml: '<Factura></Factura>',
    estado: 'emitida',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'F-002',
    ordenId: seedOrdenes[1].id,
    clienteId: seedClientes[1].id,
    clienteRazonSocial: seedClientes[1].razonSocial,
    clienteNumeroDoc: seedClientes[1].numeroDoc,
    items: [createFacturaItem({ unitario: 1500, subtotal: 1500 })],
    subtotal: 1500,
    igv: 270,
    detraccion: 60,
    total: 1710,
    xml: '<Factura></Factura>',
    estado: 'emitida',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'F-003',
    ordenId: seedOrdenes[2].id,
    clienteId: seedClientes[2].id,
    clienteRazonSocial: seedClientes[2].razonSocial,
    clienteNumeroDoc: seedClientes[2].numeroDoc,
    items: [createFacturaItem({ unitario: 800, subtotal: 800 })],
    subtotal: 800,
    igv: 144,
    detraccion: 32,
    total: 912,
    xml: '<Factura></Factura>',
    estado: 'cancelada',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'F-004',
    ordenId: seedOrdenes[3].id,
    clienteId: seedClientes[3].id,
    clienteRazonSocial: seedClientes[3].razonSocial,
    clienteNumeroDoc: seedClientes[3].numeroDoc,
    items: [createFacturaItem({ unitario: 2000, subtotal: 2000 })],
    subtotal: 2000,
    igv: 360,
    detraccion: 80,
    total: 2280,
    xml: '<Factura></Factura>',
    estado: 'emitida',
    createdAt: new Date(),
  },
  {
    id: uuidv4(),
    numero: 'F-005',
    ordenId: seedOrdenes[4].id,
    clienteId: seedClientes[4].id,
    clienteRazonSocial: seedClientes[4].razonSocial,
    clienteNumeroDoc: seedClientes[4].numeroDoc,
    items: [createFacturaItem({ unitario: 1200, subtotal: 1200 })],
    subtotal: 1200,
    igv: 216,
    detraccion: 48,
    total: 1368,
    xml: '<Factura></Factura>',
    estado: 'emitida',
    createdAt: new Date(),
  },
];

export const seedUsuarios: Usuario[] = [
  { id: uuidv4(), email: 'admin@demo.pe', nombre: 'Administrador', rol: 'admin', activo: true },
  { id: uuidv4(), email: 'operador@demo.pe', nombre: 'Operador', rol: 'operador', activo: true },
  { id: uuidv4(), email: 'conductor@demo.pe', nombre: 'Conductor', rol: 'conductor', activo: true },
];
