/**
 * Datos de ejemplo de la demo de telemedicina (jornada del jueves 8 de octubre de 2026).
 * La IPS, los pacientes, las EPS, la prepagada, los profesionales, los documentos y los
 * valores son ficticios. Los valores en COP son de ejemplo y no son tarifas oficiales.
 */
import type { Attention, Cie10, L, LabOrder, MedPreset, Patient, Payer, PayerKind, Specialty } from './types';

/** Fecha y hora "actual" de la jornada de ejemplo (fijas para que la demo sea determinista). */
export const DEMO_DATE = '2026-10-08';
export const DEMO_CLOCK = '09:30';

export const IPS = {
  name: 'IPS Altavista Salud',
  nit: '901.487.236-1',
  /** Código de habilitación de ejemplo (12 dígitos). */
  code: '110019999901',
  city: { es: 'Bogotá D. C.', en: 'Bogotá, Colombia' },
  invoicePrefix: 'ALTV',
};

export const PROFESSIONAL = { name: 'Dra. Patricia Vargas', reg: 'RM 52-1187 (ejemplo)' };

export const PAYERS: Payer[] = [
  { id: 'cordillera', name: 'EPS Cordillera', kind: 'eps' },
  { id: 'sabana', name: 'EPS Sabana Vital', kind: 'eps' },
  { id: 'horizonte', name: 'Horizonte Medicina Prepagada', kind: 'prepaid' },
  { id: 'particular', name: { es: 'Particular', en: 'Self-pay' }, kind: 'private' },
];

/** Lo que paga el paciente según el tipo de pagador (ejemplo): cuota moderadora (EPS) y bono (prepagada). */
export const PATIENT_SHARE: Record<Exclude<PayerKind, 'private'>, number> = {
  eps: 5200,
  prepaid: 28000,
};

export const SPECIALTIES: Specialty[] = [
  { key: 'general', pro: 'Dra. Patricia Vargas', reg: 'RM 52-1187', tariff: { private: 65000, eps: 45000, prepaid: 58000 }, cups: '890201' },
  { key: 'pedia', pro: 'Dr. Andrés Mejía', reg: 'RM 25-3304', tariff: { private: 95000, eps: 62000, prepaid: 80000 }, cups: '890283' },
  { key: 'derma', pro: 'Dr. Felipe Rojas', reg: 'RM 76-2290', tariff: { private: 120000, eps: 78000, prepaid: 98000 }, cups: '890242' },
  { key: 'internal', pro: 'Dra. Camila Ríos', reg: 'RM 05-4471', tariff: { private: 130000, eps: 82000, prepaid: 105000 }, cups: '890266' },
  { key: 'psych', pro: 'Ps. Iván Cárdenas', reg: 'TP 11-0938', tariff: { private: 90000, eps: 55000, prepaid: 75000 }, cups: '890208' },
];

/** Festivos de Colombia 2026 (Ley 51 de 1983). */
export const HOLIDAYS_CO_2026 = new Set([
  '2026-01-01',
  '2026-01-12',
  '2026-03-23',
  '2026-04-02',
  '2026-04-03',
  '2026-05-01',
  '2026-05-18',
  '2026-06-08',
  '2026-06-15',
  '2026-06-29',
  '2026-07-20',
  '2026-08-07',
  '2026-08-17',
  '2026-10-12',
  '2026-11-02',
  '2026-11-16',
  '2026-12-08',
  '2026-12-25',
]);

export const WEEKDAY_SLOTS = ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30', '14:00', '14:30', '15:00', '15:30', '16:00', '16:30'];
export const SATURDAY_SLOTS = ['08:00', '08:30', '09:00', '09:30', '10:00', '10:30', '11:00', '11:30'];

export const INITIAL_PATIENTS: Patient[] = [
  {
    id: 'p1',
    name: 'María González',
    age: 54,
    sex: 'F',
    docType: 'CC',
    doc: '41.220.118',
    blood: 'O+',
    payerId: 'cordillera',
    reason: {
      es: 'Dolor en el pecho opresivo desde hace 40 minutos, con sudoración',
      en: 'Crushing chest pain for 40 minutes, with sweating',
    },
    priority: 'red',
    waitMin: 4,
    status: 'waiting',
    allergies: [{ label: { es: 'Penicilina', en: 'Penicillin' }, cls: 'penicillin' }],
    history: [
      { es: 'Hipertensión arterial', en: 'High blood pressure' },
      { es: 'Dislipidemia', en: 'Dyslipidemia' },
    ],
    meds: [
      { name: { es: 'Losartán', en: 'Losartan' }, dose: '50 mg', freq: { es: 'cada 24 h', en: 'every 24 h' } },
      { name: { es: 'Atorvastatina', en: 'Atorvastatin' }, dose: '20 mg', freq: { es: 'en la noche', en: 'at night' } },
    ],
    vitals: { hr: 102, bp: '152/96', source: 'preconsult' },
    pastConsults: [
      {
        date: '2026-08-20',
        spec: 'internal',
        notes: { es: 'Control de hipertensión. Se ajusta la dosis de losartán.', en: 'Blood pressure follow-up. Losartan dose adjusted.' },
      },
      { date: '2026-02-03', spec: 'general', notes: { es: 'Cefalea tensional.', en: 'Tension headache.' } },
    ],
    preconsult: {
      reason: { es: 'Dolor en el pecho opresivo desde hace 40 minutos, con sudoración', en: 'Crushing chest pain for 40 minutes, with sweating' },
      onset: { es: 'Hace 40 minutos', en: '40 minutes ago' },
      intensity: 8,
      prev: { es: 'Ninguno', en: 'None' },
      temp: '',
      bp: '152/96',
      consentTele: true,
      consentData: true,
      consentRec: false,
      at: '09:26',
    },
    script: [{ es: 'Sí, todavía me duele el pecho.', en: 'Yes, my chest still hurts.' }],
    labs: [
      { test: { es: 'Colesterol LDL', en: 'LDL cholesterol' }, value: '142 mg/dL', ref: '< 130', flag: 'high', date: '2026-08-20' },
      { test: { es: 'Colesterol total', en: 'Total cholesterol' }, value: '228 mg/dL', ref: '< 200', flag: 'high', date: '2026-08-20' },
      { test: { es: 'Glucosa en ayunas', en: 'Fasting glucose' }, value: '98 mg/dL', ref: '70 - 100', flag: 'normal', date: '2026-08-20' },
      {
        test: { es: 'Creatinina', en: 'Creatinine' },
        value: { es: '0,9 mg/dL', en: '0.9 mg/dL' },
        ref: { es: '0,6 - 1,1', en: '0.6 - 1.1' },
        flag: 'normal',
        date: '2026-08-20',
      },
    ],
  },
  {
    id: 'p2',
    name: 'Carlos Rodríguez',
    age: 38,
    sex: 'M',
    docType: 'CC',
    doc: '1.020.554.881',
    blood: 'A+',
    payerId: 'sabana',
    reason: { es: 'Tos seca y fiebre de 38,5 °C desde hace 3 días', en: 'Dry cough and 38.5 °C fever for 3 days' },
    priority: 'yellow',
    waitMin: 9,
    status: 'waiting',
    allergies: [],
    history: [{ es: 'Asma leve intermitente', en: 'Mild intermittent asthma' }],
    meds: [{ name: { es: 'Salbutamol inhalador', en: 'Salbutamol inhaler' }, dose: '100 mcg', freq: { es: 'si lo necesita', en: 'as needed' } }],
    vitals: { hr: 92, temp: 38.4, spo2: 96, source: 'preconsult' },
    pastConsults: [
      { date: '2025-11-22', spec: 'internal', notes: { es: 'Exacerbación leve de asma. Hemograma normal.', en: 'Mild asthma flare-up. Normal blood count.' } },
    ],
    preconsult: {
      reason: { es: 'Tos seca y fiebre de 38,5 °C desde hace 3 días', en: 'Dry cough and 38.5 °C fever for 3 days' },
      onset: { es: 'Hace 3 días', en: '3 days ago' },
      intensity: 5,
      prev: { es: 'Acetaminofén cada 8 horas', en: 'Acetaminophen every 8 hours' },
      temp: '38.4',
      bp: '',
      consentTele: true,
      consentData: true,
      consentRec: true,
      at: '09:20',
    },
    script: [
      { es: 'Empezó el lunes, con fiebre en la noche de hasta 38,5.', en: 'It started on Monday, with fever at night up to 38.5.' },
      { es: 'No me falta el aire, pero la tos no me deja dormir.', en: "I'm not short of breath, but the cough keeps me up at night." },
      {
        es: 'He tomado acetaminofén cada 8 horas y uso el inhalador una vez al día.',
        en: "I've taken acetaminophen every 8 hours and I use the inhaler once a day.",
      },
      { es: 'Entendido. Muchas gracias, doctora.', en: 'Got it. Thank you very much, doctor.' },
    ],
    labs: [
      {
        test: { es: 'Leucocitos', en: 'White blood cells' },
        value: { es: '7,8 × 10³/µL', en: '7.8 × 10³/µL' },
        ref: { es: '4,5 - 11,0', en: '4.5 - 11.0' },
        flag: 'normal',
        date: '2025-11-22',
      },
      {
        test: { es: 'Hemoglobina', en: 'Hemoglobin' },
        value: { es: '15,1 g/dL', en: '15.1 g/dL' },
        ref: { es: '13,5 - 17,5', en: '13.5 - 17.5' },
        flag: 'normal',
        date: '2025-11-22',
      },
      { test: { es: 'Plaquetas', en: 'Platelets' }, value: '265 × 10³/µL', ref: '150 - 450', flag: 'normal', date: '2025-11-22' },
    ],
  },
  {
    id: 'p3',
    name: 'Ana Martínez',
    age: 29,
    sex: 'F',
    docType: 'CC',
    doc: '1.018.477.230',
    blood: 'B-',
    payerId: 'horizonte',
    reason: { es: 'Erupción en la piel con picazón en los brazos desde hace 5 días', en: 'Itchy skin rash on the arms for 5 days' },
    priority: 'green',
    waitMin: 16,
    status: 'waiting',
    allergies: [{ label: { es: 'Sulfas', en: 'Sulfa drugs' }, cls: 'sulfa' }],
    history: [{ es: 'Dermatitis atópica', en: 'Atopic dermatitis' }],
    meds: [],
    vitals: { temp: 36.5, source: 'preconsult' },
    pastConsults: [{ date: '2025-08-04', spec: 'derma', notes: { es: 'Brote leve. Hidratación de la piel.', en: 'Mild flare-up. Skin moisturizing.' } }],
    preconsult: {
      reason: { es: 'Erupción en la piel con picazón en los brazos desde hace 5 días', en: 'Itchy skin rash on the arms for 5 days' },
      onset: { es: 'Hace 5 días', en: '5 days ago' },
      intensity: 4,
      prev: { es: 'Crema hidratante', en: 'Moisturizing cream' },
      temp: '36.5',
      bp: '',
      consentTele: true,
      consentData: true,
      consentRec: false,
      at: '09:13',
    },
    script: [
      { es: 'Me salió después de cambiar de jabón.', en: 'It appeared after I changed soap.' },
      { es: 'No tengo fiebre ni hinchazón en la cara.', en: 'I have no fever or facial swelling.' },
      { es: 'Listo, ya envío la foto por aquí.', en: "Sure, I'm sending the photo here." },
      { es: 'Gracias, doctora.', en: 'Thank you, doctor.' },
    ],
    labs: [],
  },
  {
    id: 'p4',
    name: 'Pedro López',
    age: 67,
    sex: 'M',
    docType: 'CC',
    doc: '17.332.901',
    blood: 'AB+',
    payerId: 'cordillera',
    reason: {
      es: 'Control de diabetes e hipertensión; mareo leve al levantarse',
      en: 'Diabetes and blood pressure follow-up; mild dizziness when standing up',
    },
    priority: 'yellow',
    waitMin: 12,
    status: 'waiting',
    allergies: [{ label: { es: 'Ácido acetilsalicílico', en: 'Aspirin' }, cls: 'nsaid' }],
    history: [
      { es: 'Diabetes mellitus tipo 2', en: 'Type 2 diabetes' },
      { es: 'Hipertensión arterial', en: 'High blood pressure' },
    ],
    meds: [
      { name: { es: 'Metformina', en: 'Metformin' }, dose: '850 mg', freq: { es: 'cada 12 h', en: 'every 12 h' } },
      { name: { es: 'Enalapril', en: 'Enalapril' }, dose: '10 mg', freq: { es: 'cada 24 h', en: 'every 24 h' } },
    ],
    vitals: { bp: '148/92', glucose: 182, hr: 78, source: 'homeDevices' },
    pastConsults: [
      { date: '2026-09-28', spec: 'internal', notes: { es: 'Control glucémico. Se piden laboratorios.', en: 'Glucose follow-up. Lab tests ordered.' } },
    ],
    preconsult: {
      reason: {
        es: 'Control de diabetes e hipertensión; mareo leve al levantarse',
        en: 'Diabetes and blood pressure follow-up; mild dizziness when standing up',
      },
      onset: { es: 'Hace 1 semana', en: '1 week ago' },
      intensity: 3,
      prev: { es: 'Metformina y enalapril', en: 'Metformin and enalapril' },
      temp: '',
      bp: '148/92',
      consentTele: true,
      consentData: true,
      consentRec: true,
      at: '09:17',
    },
    script: [
      { es: 'En la mañana me tomé la glucosa: 182.', en: 'I checked my glucose this morning: 182.' },
      { es: 'El mareo me da cuando me paro rápido de la cama.', en: 'I get dizzy when I get out of bed quickly.' },
      { es: 'Sí, tomo la metformina con el desayuno y con la comida.', en: 'Yes, I take metformin with breakfast and dinner.' },
      { es: 'De acuerdo, gracias.', en: 'All right, thank you.' },
    ],
    labs: [
      {
        test: { es: 'Hemoglobina glicada (HbA1c)', en: 'Glycated hemoglobin (HbA1c)' },
        value: { es: '8,1 %', en: '8.1 %' },
        ref: { es: '< 7,0', en: '< 7.0' },
        flag: 'high',
        date: '2026-09-28',
      },
      { test: { es: 'Glucosa en ayunas', en: 'Fasting glucose' }, value: '168 mg/dL', ref: '70 - 100', flag: 'high', date: '2026-09-28' },
      {
        test: { es: 'Creatinina', en: 'Creatinine' },
        value: { es: '1,1 mg/dL', en: '1.1 mg/dL' },
        ref: { es: '0,7 - 1,3', en: '0.7 - 1.3' },
        flag: 'normal',
        date: '2026-09-28',
      },
      { test: { es: 'Microalbuminuria', en: 'Urine microalbumin' }, value: '38 mg/g', ref: '< 30', flag: 'high', date: '2026-09-28' },
      { test: { es: 'Colesterol LDL', en: 'LDL cholesterol' }, value: '96 mg/dL', ref: '< 100', flag: 'normal', date: '2026-09-28' },
    ],
  },
  {
    id: 'p5',
    name: 'Laura Pérez',
    age: 8,
    sex: 'F',
    docType: 'TI',
    doc: '1.135.220.776',
    blood: 'O+',
    payerId: 'sabana',
    reason: { es: 'Dolor de oído derecho desde ayer, sin fiebre alta', en: 'Right ear pain since yesterday, no high fever' },
    priority: 'green',
    waitMin: 22,
    status: 'waiting',
    allergies: [],
    history: [{ es: 'Otitis media recurrente', en: 'Recurrent middle ear infection' }],
    meds: [],
    vitals: { temp: 37.4, source: 'preconsult' },
    pastConsults: [
      { date: '2025-12-18', spec: 'pedia', notes: { es: 'Otitis media aguda. Tratamiento completo.', en: 'Acute middle ear infection. Full treatment.' } },
    ],
    preconsult: {
      reason: { es: 'Dolor de oído derecho desde ayer, sin fiebre alta', en: 'Right ear pain since yesterday, no high fever' },
      onset: { es: 'Desde ayer', en: 'Since yesterday' },
      intensity: 5,
      prev: { es: 'Acetaminofén en jarabe', en: 'Acetaminophen syrup' },
      temp: '37.4',
      bp: '',
      consentTele: true,
      consentData: true,
      consentRec: false,
      at: '09:08',
    },
    guardian: { es: 'Acudiente: Diana Pérez (madre)', en: 'Guardian: Diana Pérez (mother)' },
    script: [
      { es: 'Soy la mamá. Le empezó ayer en la tarde.', en: "I'm her mother. It started yesterday afternoon." },
      { es: 'Tuvo 37,4 de temperatura en la noche.', en: 'She had a temperature of 37.4 last night.' },
      { es: 'No le ha salido líquido del oído.', en: 'No fluid has come out of her ear.' },
      { es: 'Muchas gracias, doctora.', en: 'Thank you very much, doctor.' },
    ],
    labs: [],
  },
];

/** Catálogo reducido de diagnósticos CIE-10 para la demo. */
export const CIE10: Cie10[] = [
  {
    code: 'J06.9',
    label: { es: 'Infección aguda de las vías respiratorias superiores, no especificada', en: 'Acute upper respiratory infection, unspecified' },
  },
  { code: 'J00', label: { es: 'Rinofaringitis aguda (resfriado común)', en: 'Acute nasopharyngitis (common cold)' } },
  { code: 'J20.9', label: { es: 'Bronquitis aguda, no especificada', en: 'Acute bronchitis, unspecified' } },
  { code: 'J45.9', label: { es: 'Asma, no especificada', en: 'Asthma, unspecified' } },
  { code: 'R05', label: { es: 'Tos', en: 'Cough' } },
  { code: 'R50.9', label: { es: 'Fiebre, no especificada', en: 'Fever, unspecified' } },
  { code: 'L20.9', label: { es: 'Dermatitis atópica, no especificada', en: 'Atopic dermatitis, unspecified' } },
  { code: 'L23.9', label: { es: 'Dermatitis alérgica de contacto, de causa no especificada', en: 'Allergic contact dermatitis, unspecified cause' } },
  { code: 'L50.9', label: { es: 'Urticaria, no especificada', en: 'Urticaria, unspecified' } },
  { code: 'H66.9', label: { es: 'Otitis media, no especificada', en: 'Otitis media, unspecified' } },
  { code: 'H92.0', label: { es: 'Otalgia', en: 'Otalgia (ear pain)' } },
  { code: 'I10', label: { es: 'Hipertensión esencial (primaria)', en: 'Essential (primary) hypertension' } },
  { code: 'E11.9', label: { es: 'Diabetes mellitus tipo 2, sin mención de complicación', en: 'Type 2 diabetes mellitus without complications' } },
  { code: 'R42', label: { es: 'Mareo y desvanecimiento', en: 'Dizziness and giddiness' } },
  { code: 'I95.1', label: { es: 'Hipotensión ortostática', en: 'Orthostatic hypotension' } },
  { code: 'R51', label: { es: 'Cefalea', en: 'Headache' } },
  { code: 'G43.9', label: { es: 'Migraña, no especificada', en: 'Migraine, unspecified' } },
  { code: 'R07.4', label: { es: 'Dolor en el pecho, no especificado', en: 'Chest pain, unspecified' } },
  { code: 'F41.1', label: { es: 'Trastorno de ansiedad generalizada', en: 'Generalized anxiety disorder' } },
  { code: 'K29.7', label: { es: 'Gastritis, no especificada', en: 'Gastritis, unspecified' } },
  { code: 'N39.0', label: { es: 'Infección de vías urinarias, sitio no especificado', en: 'Urinary tract infection, site not specified' } },
  { code: 'M54.5', label: { es: 'Lumbago no especificado', en: 'Low back pain' } },
];

/** Medicamentos frecuentes para agregar con un clic (texto editable). */
export const MED_PRESETS: MedPreset[] = [
  {
    id: 'acetaminofen',
    name: { es: 'Acetaminofén 500 mg tableta', en: 'Acetaminophen 500 mg tablet' },
    dose: { es: '1 tableta', en: '1 tablet' },
    freq: { es: 'Cada 8 horas', en: 'Every 8 hours' },
    duration: { es: '5 días', en: '5 days' },
    instructions: { es: 'Solo si hay fiebre o dolor. No exceder 4 tabletas al día.', en: 'Only for fever or pain. Do not exceed 4 tablets a day.' },
  },
  {
    id: 'ibuprofeno',
    name: { es: 'Ibuprofeno 400 mg tableta', en: 'Ibuprofen 400 mg tablet' },
    dose: { es: '1 tableta', en: '1 tablet' },
    freq: { es: 'Cada 8 horas', en: 'Every 8 hours' },
    duration: { es: '3 días', en: '3 days' },
    instructions: { es: 'Tomar con alimentos.', en: 'Take with food.' },
    cls: 'nsaid',
  },
  {
    id: 'loratadina',
    name: { es: 'Loratadina 10 mg tableta', en: 'Loratadine 10 mg tablet' },
    dose: { es: '1 tableta', en: '1 tablet' },
    freq: { es: 'Cada 24 horas', en: 'Every 24 hours' },
    duration: { es: '7 días', en: '7 days' },
    instructions: { es: 'Puede producir somnolencia leve.', en: 'May cause mild drowsiness.' },
  },
  {
    id: 'hidrocortisona',
    name: { es: 'Hidrocortisona crema 1 %', en: 'Hydrocortisone 1 % cream' },
    dose: { es: 'Capa delgada', en: 'Thin layer' },
    freq: { es: 'Cada 12 horas', en: 'Every 12 hours' },
    duration: { es: '7 días', en: '7 days' },
    instructions: { es: 'Aplicar solo en la zona afectada. No usar en la cara.', en: 'Apply only to the affected area. Do not use on the face.' },
  },
  {
    id: 'salbutamol',
    name: { es: 'Salbutamol inhalador 100 mcg', en: 'Salbutamol inhaler 100 mcg' },
    dose: { es: '2 inhalaciones', en: '2 puffs' },
    freq: { es: 'Cada 6 horas si hay tos o silbido', en: 'Every 6 hours for cough or wheezing' },
    duration: { es: '7 días', en: '7 days' },
    instructions: { es: 'Usar con inhalocámara.', en: 'Use with a spacer.' },
  },
  {
    id: 'amoxicilina',
    name: { es: 'Amoxicilina 500 mg cápsula', en: 'Amoxicillin 500 mg capsule' },
    dose: { es: '1 cápsula', en: '1 capsule' },
    freq: { es: 'Cada 8 horas', en: 'Every 8 hours' },
    duration: { es: '7 días', en: '7 days' },
    instructions: { es: 'No suspender antes de terminar el tratamiento.', en: 'Do not stop before finishing the treatment.' },
    cls: 'penicillin',
  },
  {
    id: 'tmpsmx',
    name: { es: 'Trimetoprim/sulfametoxazol 160/800 mg', en: 'Trimethoprim/sulfamethoxazole 160/800 mg' },
    dose: { es: '1 tableta', en: '1 tablet' },
    freq: { es: 'Cada 12 horas', en: 'Every 12 hours' },
    duration: { es: '5 días', en: '5 days' },
    instructions: { es: 'Tomar con abundante agua.', en: 'Take with plenty of water.' },
    cls: 'sulfa',
  },
];

export const LAB_ORDERS: LabOrder[] = [
  { id: 'hemograma', label: { es: 'Hemograma completo', en: 'Complete blood count' } },
  { id: 'pcr', label: { es: 'Proteína C reactiva (PCR)', en: 'C-reactive protein (CRP)' } },
  { id: 'glucosa', label: { es: 'Glucosa en ayunas', en: 'Fasting glucose' } },
  { id: 'hba1c', label: { es: 'Hemoglobina glicada (HbA1c)', en: 'Glycated hemoglobin (HbA1c)' } },
  { id: 'lipidos', label: { es: 'Perfil lipídico', en: 'Lipid panel' } },
  { id: 'creatinina', label: { es: 'Creatinina', en: 'Creatinine' } },
  { id: 'uroanalisis', label: { es: 'Uroanálisis', en: 'Urinalysis' } },
  { id: 'tsh', label: { es: 'TSH', en: 'TSH' } },
];

const rx = (number: string, signedAt: string, meds: { name: L; dose: L; freq: L; duration: L }[]) => ({
  number,
  signedAt,
  meds: meds.map((m) => ({ instructions: '', ...m })),
});

/** Atenciones finalizadas más temprano en la jornada de ejemplo (alimentan Pagos y facturación). */
export const INITIAL_ATTENTIONS: Attention[] = [
  {
    id: 'AT-2026-1041',
    kind: 'consult',
    patientName: 'Jorge Ramírez',
    docType: 'CC',
    doc: '79.554.302',
    payerId: 'cordillera',
    spec: 'general',
    date: DEMO_DATE,
    time: '08:00',
    durationMin: 14,
    dx: { code: 'J00', label: { es: 'Rinofaringitis aguda (resfriado común)', en: 'Acute nasopharyngitis (common cold)' } },
    value: 45000,
    patientShare: 5200,
    payerShare: 39800,
    payStatus: 'paid',
    payMethod: 'pse',
    payRef: 'SIM-480112',
    invoice: 'ALTV-10451',
    rips: true,
    rx: rx('RX-2026-0146', '08:13', [
      { name: MED_PRESETS[0].name, dose: MED_PRESETS[0].dose, freq: MED_PRESETS[0].freq, duration: { es: '3 días', en: '3 days' } },
    ]),
    orders: [],
    soap: null,
  },
  {
    id: 'AT-2026-1042',
    kind: 'consult',
    patientName: 'Sofía Herrera',
    docType: 'CC',
    doc: '1.032.448.917',
    payerId: 'particular',
    spec: 'psych',
    date: DEMO_DATE,
    time: '08:10',
    durationMin: 48,
    dx: { code: 'F41.1', label: { es: 'Trastorno de ansiedad generalizada', en: 'Generalized anxiety disorder' } },
    value: 90000,
    patientShare: 90000,
    payerShare: 0,
    payStatus: 'paid',
    payMethod: 'card',
    payRef: 'SIM-480127',
    invoice: 'ALTV-10452',
    rips: true,
    rx: null,
    orders: [],
    soap: null,
  },
  {
    id: 'AT-2026-1043',
    kind: 'consult',
    patientName: 'Luis Castaño',
    docType: 'CC',
    doc: '80.211.765',
    payerId: 'horizonte',
    spec: 'derma',
    date: DEMO_DATE,
    time: '08:40',
    durationMin: 18,
    dx: { code: 'L23.9', label: { es: 'Dermatitis alérgica de contacto, de causa no especificada', en: 'Allergic contact dermatitis, unspecified cause' } },
    value: 98000,
    patientShare: 28000,
    payerShare: 70000,
    payStatus: 'pending',
    invoice: 'ALTV-10453',
    rips: true,
    rx: rx('RX-2026-0147', '08:57', [{ name: MED_PRESETS[3].name, dose: MED_PRESETS[3].dose, freq: MED_PRESETS[3].freq, duration: MED_PRESETS[3].duration }]),
    orders: [],
    soap: null,
  },
  {
    id: 'AT-2026-1044',
    kind: 'consult',
    patientName: 'Valentina Ortiz',
    docType: 'TI',
    doc: '1.141.302.558',
    payerId: 'sabana',
    spec: 'pedia',
    date: DEMO_DATE,
    time: '08:50',
    durationMin: 16,
    dx: {
      code: 'J06.9',
      label: { es: 'Infección aguda de las vías respiratorias superiores, no especificada', en: 'Acute upper respiratory infection, unspecified' },
    },
    value: 62000,
    patientShare: 5200,
    payerShare: 56800,
    payStatus: 'paid',
    payMethod: 'wallet',
    payRef: 'SIM-480163',
    invoice: 'ALTV-10454',
    rips: true,
    rx: rx('RX-2026-0148', '09:05', [
      {
        name: { es: 'Acetaminofén jarabe 150 mg/5 mL', en: 'Acetaminophen syrup 150 mg/5 mL' },
        dose: { es: '7 mL', en: '7 mL' },
        freq: { es: 'Cada 6 horas', en: 'Every 6 hours' },
        duration: { es: '3 días', en: '3 days' },
      },
    ]),
    orders: ['hemograma'],
    soap: null,
  },
  {
    id: 'AT-2026-1045',
    kind: 'consult',
    patientName: 'Andrés Suárez',
    docType: 'CC',
    doc: '1.019.874.023',
    payerId: 'particular',
    spec: 'general',
    date: DEMO_DATE,
    time: '09:05',
    durationMin: 12,
    dx: { code: 'K29.7', label: { es: 'Gastritis, no especificada', en: 'Gastritis, unspecified' } },
    value: 65000,
    patientShare: 65000,
    payerShare: 0,
    payStatus: 'pending',
    invoice: 'ALTV-10455',
    rips: true,
    rx: null,
    orders: [],
    soap: null,
  },
];

export const FIRST_ATTENTION_NUMBER = 1046;
export const FIRST_RX_NUMBER = 149;
export const FIRST_INVOICE_NUMBER = 10456;

/** Respuestas de ejemplo en el chat para pacientes creados desde la vista del paciente. */
export const GENERIC_SCRIPT = [
  { es: 'Sí, así ha sido desde que empezó.', en: "Yes, it's been like that since it started." },
  { es: 'No he tenido otros síntomas.', en: "I haven't had any other symptoms." },
  { es: 'Entendido. Muchas gracias.', en: 'Understood. Thank you very much.' },
];
