import { PullRequest, Review } from './code-review.types';

const t = (h: number) => new Date(Date.now() - h * 3600000).toISOString();

export const pullRequests: PullRequest[] = [
  { id: 'pr_001', repo: 'koptup/backend', number: 412, title: 'feat: agregar módulo CRM', author: 'mateo', status: 'open', additions: 850, deletions: 12, filesChanged: 14, branch: 'feature/crm', reviewIds: ['rev_001', 'rev_002'], createdAt: t(48), updatedAt: t(2) },
  { id: 'pr_002', repo: 'koptup/frontend', number: 287, title: 'fix: bug en dashboard', author: 'juliana', status: 'merged', additions: 23, deletions: 8, filesChanged: 2, branch: 'fix/dashboard-bug', reviewIds: ['rev_003'], createdAt: t(72), updatedAt: t(60) },
  { id: 'pr_003', repo: 'koptup/backend', number: 413, title: 'refactor: extraer servicio de pagos', author: 'tomas', status: 'open', additions: 320, deletions: 280, filesChanged: 8, branch: 'refactor/payments', reviewIds: ['rev_004'], createdAt: t(24), updatedAt: t(5) },
  { id: 'pr_004', repo: 'koptup/infra', number: 56, title: 'chore: actualizar K8s 1.29', author: 'rafael', status: 'open', additions: 145, deletions: 90, filesChanged: 12, branch: 'chore/k8s-1.29', reviewIds: [], createdAt: t(12), updatedAt: t(12) },
  { id: 'pr_005', repo: 'koptup/frontend', number: 288, title: 'feat: tema oscuro', author: 'lucas', status: 'merged', additions: 412, deletions: 67, filesChanged: 18, branch: 'feature/dark-mode', reviewIds: ['rev_005', 'rev_006'], createdAt: t(120), updatedAt: t(96) },
  { id: 'pr_006', repo: 'koptup/backend', number: 414, title: 'fix: validación email', author: 'juliana', status: 'closed', additions: 5, deletions: 5, filesChanged: 1, branch: 'fix/email-validation', reviewIds: ['rev_007'], createdAt: t(100), updatedAt: t(80) },
  { id: 'pr_007', repo: 'koptup/backend', number: 415, title: 'feat: módulo voice-ai', author: 'mateo', status: 'open', additions: 1200, deletions: 5, filesChanged: 22, branch: 'feature/voice-ai', reviewIds: ['rev_008'], createdAt: t(6), updatedAt: t(1) },
];

export const reviews: Review[] = [
  { id: 'rev_001', pullRequestId: 'pr_001', reviewer: 'KopTup AI Bot', verdict: 'comment', summary: 'Sugerencias menores: 3 archivos exceden 300 líneas', inlineComments: 7, autoGenerated: true, createdAt: t(47), updatedAt: t(47) },
  { id: 'rev_002', pullRequestId: 'pr_001', reviewer: 'juliana', verdict: 'request-changes', summary: 'Falta tests para forecast', inlineComments: 3, autoGenerated: false, createdAt: t(24), updatedAt: t(24) },
  { id: 'rev_003', pullRequestId: 'pr_002', reviewer: 'mateo', verdict: 'approve', summary: 'LGTM', inlineComments: 0, autoGenerated: false, createdAt: t(65), updatedAt: t(65) },
  { id: 'rev_004', pullRequestId: 'pr_003', reviewer: 'KopTup AI Bot', verdict: 'approve', summary: 'Refactor sólido, cobertura de tests adecuada', inlineComments: 2, autoGenerated: true, createdAt: t(23), updatedAt: t(23) },
  { id: 'rev_005', pullRequestId: 'pr_005', reviewer: 'KopTup AI Bot', verdict: 'comment', summary: 'Accesibilidad: revisar contraste WCAG AA', inlineComments: 5, autoGenerated: true, createdAt: t(118), updatedAt: t(118) },
  { id: 'rev_006', pullRequestId: 'pr_005', reviewer: 'mateo', verdict: 'approve', summary: 'Bien hecho, mergeable', inlineComments: 1, autoGenerated: false, createdAt: t(100), updatedAt: t(100) },
  { id: 'rev_007', pullRequestId: 'pr_006', reviewer: 'mateo', verdict: 'request-changes', summary: 'No es la abstracción correcta', inlineComments: 1, autoGenerated: false, createdAt: t(90), updatedAt: t(90) },
  { id: 'rev_008', pullRequestId: 'pr_007', reviewer: 'KopTup AI Bot', verdict: 'pending', summary: 'Analizando...', inlineComments: 0, autoGenerated: true, createdAt: t(1), updatedAt: t(1) },
];
