import { BaseEntity } from '../_shared/types';

export type PrStatus = 'open' | 'merged' | 'closed';
export type ReviewVerdict = 'approve' | 'request-changes' | 'comment' | 'pending';

export interface PullRequest extends BaseEntity {
  repo: string;
  number: number;
  title: string;
  author: string;
  status: PrStatus;
  additions: number;
  deletions: number;
  filesChanged: number;
  branch: string;
  reviewIds: ReadonlyArray<string>;
}

export interface Review extends BaseEntity {
  pullRequestId: string;
  reviewer: string;
  verdict: ReviewVerdict;
  summary: string;
  inlineComments: number;
  autoGenerated: boolean;
}
