import { applyPatch, Filterable, findOrThrow, nextId, nowIso, paginate, softDelete } from '../_shared/crud';
import { DomainError, ListResult } from '../_shared/types';
import { pullRequests as seedPrs, reviews as seedReviews } from './code-review.data';
import { PullRequest, Review } from './code-review.types';

export interface CodeReviewService {
  list(q: Filterable & { repo?: string; author?: string }): ListResult<PullRequest>;
  get(id: string): PullRequest;
  create(input: Partial<PullRequest>): PullRequest;
  update(id: string, patch: Partial<PullRequest>): PullRequest;
  remove(id: string): { id: string };
  listReviews(prId: string): ReadonlyArray<Review>;
  runAiReview(prId: string): Review;
}

export class InMemoryCodeReviewService implements CodeReviewService {
  private prs: PullRequest[] = [...seedPrs];
  private reviews: Review[] = [...seedReviews];

  list(q: Filterable & { repo?: string; author?: string }): ListResult<PullRequest> {
    const base = paginate(this.prs, q, (p, n) => p.title.toLowerCase().includes(n));
    let items = base.items;
    if (q.repo) items = items.filter((p) => p.repo === q.repo);
    if (q.author) items = items.filter((p) => p.author === q.author);
    return { ...base, items };
  }
  get(id: string): PullRequest { return findOrThrow(this.prs, id, 'PullRequest'); }

  create(input: Partial<PullRequest>): PullRequest {
    if (!input.repo || !input.title || !input.author || !input.branch) {
      throw new DomainError('VALIDATION', 'repo, title, author, branch requeridos');
    }
    const p: PullRequest = {
      id: nextId('pr'),
      repo: input.repo,
      number: input.number ?? Math.floor(Math.random() * 1000),
      title: input.title,
      author: input.author,
      status: 'open',
      additions: input.additions ?? 0,
      deletions: input.deletions ?? 0,
      filesChanged: input.filesChanged ?? 0,
      branch: input.branch,
      reviewIds: [],
      createdAt: nowIso(),
      updatedAt: nowIso(),
    };
    this.prs.push(p);
    return p;
  }

  update(id: string, patch: Partial<PullRequest>): PullRequest {
    const idx = this.prs.findIndex((x) => x.id === id);
    if (idx < 0) throw new DomainError('NOT_FOUND', `PullRequest ${id}`);
    this.prs[idx] = applyPatch(this.prs[idx], patch);
    return this.prs[idx];
  }
  remove(id: string): { id: string } {
    const idx = this.prs.findIndex((x) => x.id === id);
    if (idx < 0) throw new DomainError('NOT_FOUND', `PullRequest ${id}`);
    this.prs[idx] = softDelete(this.prs[idx]);
    return { id };
  }

  listReviews(prId: string): ReadonlyArray<Review> {
    return this.reviews.filter((r) => r.pullRequestId === prId && !r.deletedAt);
  }

  runAiReview(prId: string): Review {
    const pr = findOrThrow(this.prs, prId, 'PullRequest');
    const verdict: Review['verdict'] = pr.additions > 800 ? 'request-changes' : pr.additions > 200 ? 'comment' : 'approve';
    const summary = pr.additions > 800
      ? 'PR muy grande: considera dividir en commits más pequeños'
      : pr.additions > 200
        ? 'Cambios significativos: revisar cobertura de tests'
        : 'LGTM: cambios mínimos y seguros';
    const r: Review = {
      id: nextId('rev'),
      pullRequestId: prId,
      reviewer: 'KopTup AI Bot',
      verdict,
      summary,
      inlineComments: Math.min(10, Math.floor(pr.filesChanged / 2)),
      autoGenerated: true,
      createdAt: nowIso(),
      updatedAt: nowIso(),
    };
    this.reviews.push(r);
    return r;
  }
}

export const codeReviewService: CodeReviewService = new InMemoryCodeReviewService();
