/**
 * Catálogo completo de demos Koptup + estrategia de publicación.
 * Diseñado para alimentar el generador de contenido LinkedIn.
 */

export type AnguloPost =
  | 'lanzamiento'
  | 'caso-uso'
  | 'educativo'
  | 'testimonio'
  | 'detras-camaras'
  | 'comparativa'
  | 'tip-rapido'
  | 'pregunta-engagement';

export type TonoPost = 'profesional' | 'cercano' | 'tecnico' | 'storytelling' | 'controversial';

export type TipoContenido = 'texto' | 'carrusel' | 'imagen' | 'video' | 'articulo';

export interface KoptupDemo {
  id: string;
  slug: string;
  path: string;
  titulo: string;
  tagline: string;
  industria: string;
  problemaResuelve: string;
  beneficiosClave: string[];
  publicoObjetivo: string[];
  metricaImpactante: string;
  caracteristicasIA: string[];
  emoji: string;
  hashtagsEspecificos: string[];
}

export const KOPTUP_DEMOS: KoptupDemo[] = [
  {
    id: 'chatbot',
    slug: 'chatbot',
    path: '/demo/chatbot',
    titulo: 'Chatbot Enterprise RAG',
    tagline: 'IA que responde con tus propios documentos, no inventa nada',
    industria: 'Atención al cliente / Knowledge bases',
    problemaResuelve: 'Empresas pierden horas respondiendo preguntas repetitivas y los chatbots tradicionales inventan respuestas',
    beneficiosClave: [
      'Responde citando documentos reales (no alucina)',
      'Despliegue en cualquier sitio con 1 línea de código',
      'Multi-tenant, multi-modelo, observabilidad enterprise',
      'Restricción de temas configurable',
    ],
    publicoObjetivo: ['Clínicas', 'E-commerce', 'Bufetes', 'Educación', 'Soporte interno'],
    metricaImpactante: '94% faithfulness · <1.5s latencia · cita 100% verificable',
    caracteristicasIA: ['RAG multi-source', 'Reranking', 'Citations', 'PII masking', 'Observabilidad'],
    emoji: '🤖',
    hashtagsEspecificos: ['#RAG', '#ChatbotEmpresarial', '#IAGenerativa', '#KnowledgeBase'],
  },
  {
    id: 'ecommerce',
    slug: 'ecommerce',
    path: '/demo/ecommerce',
    titulo: 'E-commerce con IA',
    tagline: 'Tienda online completa con recomendaciones inteligentes',
    industria: 'Retail / Comercio digital',
    problemaResuelve: 'Tiendas online genéricas que no convierten porque no entienden al cliente',
    beneficiosClave: [
      'Carrito + checkout + inventario en un solo lugar',
      'Recomendaciones personalizadas con IA',
      'Pasarelas locales (PSE, Nequi, Bancolombia)',
      'Panel admin con analítica de ventas',
    ],
    publicoObjetivo: ['Retailers', 'Fabricantes', 'Marketplaces', 'D2C'],
    metricaImpactante: '+30% conversión con recomendaciones IA vs catálogo estático',
    caracteristicasIA: ['Recomendador', 'Búsqueda semántica', 'Pricing dinámico', 'Detección de fraude'],
    emoji: '🛒',
    hashtagsEspecificos: ['#Ecommerce', '#RetailTech', '#Conversión', '#PagosColombia'],
  },
  {
    id: 'dashboard-ejecutivo',
    slug: 'dashboard-ejecutivo',
    path: '/demo/dashboard-ejecutivo',
    titulo: 'Dashboard Ejecutivo con IA',
    tagline: 'KPIs en tiempo real con insights generados por IA',
    industria: 'Gerencia / Business Intelligence',
    problemaResuelve: 'CEOs reciben reportes estáticos que no responden el "por qué" detrás de los números',
    beneficiosClave: [
      'KPIs financieros, ventas y operaciones en vivo',
      'Insights automáticos en lenguaje natural',
      'Alertas inteligentes ante anomalías',
      'Exportación a PDF/Excel un click',
    ],
    publicoObjetivo: ['CEOs', 'CFOs', 'Gerentes generales', 'Directores'],
    metricaImpactante: 'De 4 horas armando reportes → 30 segundos preguntando',
    caracteristicasIA: ['NL Query', 'Anomaly detection', 'Forecasting', 'Auto-insights'],
    emoji: '📊',
    hashtagsEspecificos: ['#BI', '#Analytics', '#ExecutiveDashboard', '#DataDriven'],
  },
  {
    id: 'gestor-documentos',
    slug: 'gestor-documentos',
    path: '/demo/gestor-documentos',
    titulo: 'Gestor Documental con IA',
    tagline: 'OCR + extracción de cláusulas + retención legal automática',
    industria: 'Legal / Compliance / Admin',
    problemaResuelve: 'Archivos PDF muertos que nadie revisa hasta que hay una auditoría',
    beneficiosClave: [
      'OCR multi-idioma con corrección IA',
      'Detección automática de cláusulas críticas',
      'Políticas de retención y archivo legal',
      'Versionado + diff visual entre contratos',
    ],
    publicoObjetivo: ['Bufetes', 'Áreas legales', 'Compliance', 'Notarías', 'RRHH'],
    metricaImpactante: 'Revisión de contrato: 2 horas → 90 segundos',
    caracteristicasIA: ['OCR avanzado', 'Clause extraction', 'Document Q&A', 'Risk scoring'],
    emoji: '📄',
    hashtagsEspecificos: ['#LegalTech', '#DocumentAI', '#Compliance', '#OCR'],
  },
  {
    id: 'sistema-reservas',
    slug: 'sistema-reservas',
    path: '/demo/sistema-reservas',
    titulo: 'Sistema de Reservas Online',
    tagline: 'Calendario inteligente con notificaciones automáticas',
    industria: 'Servicios / Hospitalidad / Salud',
    problemaResuelve: 'Negocios pierden citas por agendas en cuadernos y WhatsApp informal',
    beneficiosClave: [
      'Disponibilidad en tiempo real multi-recurso',
      'Notificaciones WhatsApp + email automáticas',
      'Confirmación / cancelación self-service',
      'Anti-overbooking',
    ],
    publicoObjetivo: ['Clínicas', 'Restaurantes', 'Salones', 'Hoteles', 'Consultorios'],
    metricaImpactante: '-65% no-shows con recordatorios automáticos',
    caracteristicasIA: ['Slot optimization', 'No-show prediction', 'Smart scheduling'],
    emoji: '📅',
    hashtagsEspecificos: ['#Booking', '#HospitalityTech', '#Citas', '#WhatsAppAPI'],
  },
  {
    id: 'gestor-contenido',
    slug: 'gestor-contenido',
    path: '/demo/gestor-contenido',
    titulo: 'Gestor de Contenido CMS + IA',
    tagline: 'Genera, edita y publica contenido corporativo en segundos',
    industria: 'Marketing / Comunicaciones',
    problemaResuelve: 'Equipos pierden días redactando emails, propuestas y posts cuando podrían usar IA',
    beneficiosClave: [
      'Plantillas profesionales (email, propuesta, social)',
      'Asistentes IA para tono y longitud',
      'Editor + preview en tiempo real',
      'Versionado y workflow editorial',
    ],
    publicoObjetivo: ['Marketing', 'Ventas', 'Comunicación interna', 'Startups'],
    metricaImpactante: 'Propuesta comercial: 3 horas → 15 minutos',
    caracteristicasIA: ['Generación', 'Reescritura', 'SEO', 'Personalización por audiencia'],
    emoji: '✍️',
    hashtagsEspecificos: ['#CMS', '#ContentMarketing', '#IAGenerativa', '#Copywriting'],
  },
  {
    id: 'control-proyectos',
    slug: 'control-proyectos',
    path: '/demo/control-proyectos',
    titulo: 'Control de Proyectos PM + IA',
    tagline: 'Gantt + Kanban + predicción de delays',
    industria: 'Project Management / Construcción / Software',
    problemaResuelve: 'Proyectos que se atrasan sin que nadie vea las señales tempranas',
    beneficiosClave: [
      'Gantt interactivo + Kanban + timeline',
      'Predicción de delays con IA',
      'Asignación inteligente de recursos',
      'Reportes ejecutivos automáticos',
    ],
    publicoObjetivo: ['PMOs', 'Constructoras', 'Software houses', 'Consultorías'],
    metricaImpactante: '-40% delays detectando riesgos 3 semanas antes',
    caracteristicasIA: ['Delay prediction', 'Resource optimization', 'Risk scoring'],
    emoji: '📋',
    hashtagsEspecificos: ['#ProjectManagement', '#Gantt', '#PMO', '#Agile'],
  },
  {
    id: 'crm-ia',
    slug: 'crm-ia',
    path: '/demo/crm-ia',
    titulo: 'CRM con Inteligencia Artificial',
    tagline: 'Pipeline + lead scoring + secuencias automáticas',
    industria: 'Ventas B2B',
    problemaResuelve: 'Vendedores pierden tiempo en leads fríos y olvidan seguimientos clave',
    beneficiosClave: [
      'Lead scoring automático',
      'Secuencias de outreach personalizadas',
      'Predicción de cierre por deal',
      'Análisis de sentimiento en emails',
    ],
    publicoObjetivo: ['Equipos comerciales B2B', 'SDRs', 'Account Executives'],
    metricaImpactante: '+45% tasa de cierre priorizando leads con IA',
    caracteristicasIA: ['Lead scoring', 'Sentiment', 'Next best action', 'Email gen'],
    emoji: '💼',
    hashtagsEspecificos: ['#CRM', '#SalesAI', '#B2BSales', '#LeadScoring'],
  },
  {
    id: 'erp',
    slug: 'erp',
    path: '/demo/erp',
    titulo: 'ERP Modular',
    tagline: 'Inventario + finanzas + producción en un solo lugar',
    industria: 'Manufactura / Distribución / PyMEs',
    problemaResuelve: 'Empresas con 5 sistemas distintos que no se hablan',
    beneficiosClave: [
      'Inventario en tiempo real multi-bodega',
      'Contabilidad integrada',
      'Producción + órdenes de trabajo',
      'API para integrar con cualquier sistema',
    ],
    publicoObjetivo: ['Manufactureras', 'Distribuidoras', 'PyMEs en crecimiento'],
    metricaImpactante: 'Cierre contable: 5 días → 4 horas',
    caracteristicasIA: ['Forecast demanda', 'Anomaly detection', 'Auto-reorder'],
    emoji: '🏭',
    hashtagsEspecificos: ['#ERP', '#Manufactura', '#GestiónEmpresarial'],
  },
  {
    id: 'helpdesk-ia',
    slug: 'helpdesk-ia',
    path: '/demo/helpdesk-ia',
    titulo: 'Helpdesk con IA',
    tagline: 'Tickets + auto-resolución + SLA tracking',
    industria: 'Soporte / IT / Customer Success',
    problemaResuelve: 'Equipos de soporte saturados resolviendo lo mismo todos los días',
    beneficiosClave: [
      'Auto-clasificación y enrutamiento',
      'Sugerencias de respuesta basadas en KB',
      'SLA tracking en tiempo real',
      'Detección de tickets escalados',
    ],
    publicoObjetivo: ['IT Support', 'Customer Success', 'Mesas de ayuda'],
    metricaImpactante: '60% de tickets resueltos sin tocar humano',
    caracteristicasIA: ['Auto-classify', 'Suggested replies', 'Sentiment routing'],
    emoji: '🎧',
    hashtagsEspecificos: ['#Helpdesk', '#ITSM', '#CustomerSuccess', '#SLA'],
  },
  {
    id: 'lms',
    slug: 'lms',
    path: '/demo/lms',
    titulo: 'LMS para Capacitación',
    tagline: 'Cursos + evaluaciones + ruta de aprendizaje personalizada',
    industria: 'Educación / Capacitación corporativa',
    problemaResuelve: 'Programas de training que nadie completa porque son aburridos y genéricos',
    beneficiosClave: [
      'Cursos multimedia con quizzes',
      'Ruta personalizada por estudiante',
      'Certificados verificables',
      'Reportes de avance para HR',
    ],
    publicoObjetivo: ['RRHH', 'Universidades corporativas', 'EdTech'],
    metricaImpactante: '+80% completion rate con rutas adaptativas',
    caracteristicasIA: ['Adaptive learning', 'Auto-quiz gen', 'Tutoría virtual'],
    emoji: '🎓',
    hashtagsEspecificos: ['#LMS', '#CorporateLearning', '#EdTech', '#Upskilling'],
  },
  {
    id: 'telemedicina',
    slug: 'telemedicina',
    path: '/demo/telemedicina',
    titulo: 'Plataforma de Telemedicina',
    tagline: 'Videoconsulta + historia clínica + receta digital',
    industria: 'Salud',
    problemaResuelve: 'Pacientes en zonas rurales sin acceso a especialistas',
    beneficiosClave: [
      'Videollamada con sala virtual',
      'Historia clínica electrónica',
      'Receta digital firmada',
      'Cumplimiento HIPAA / Habeas Data',
    ],
    publicoObjetivo: ['Clínicas', 'EPS', 'Consultorios especializados'],
    metricaImpactante: 'Acceso a especialista: días → minutos',
    caracteristicasIA: ['Triage automático', 'Transcripción de consulta', 'Resumen clínico'],
    emoji: '🩺',
    hashtagsEspecificos: ['#Telemedicina', '#HealthTech', '#eHealth'],
  },
  {
    id: 'facturacion-electronica',
    slug: 'facturacion-electronica',
    path: '/demo/facturacion-electronica',
    titulo: 'Facturación Electrónica DIAN',
    tagline: 'Emisión + validación + reportes fiscales',
    industria: 'Contabilidad / Fiscal Colombia',
    problemaResuelve: 'Empresas multadas por facturación electrónica mal emitida',
    beneficiosClave: [
      'Emisión validada DIAN en tiempo real',
      'Notas crédito / débito',
      'Reportes fiscales automáticos',
      'Integración con cualquier ERP',
    ],
    publicoObjetivo: ['Contadores', 'PyMEs', 'Empresas medianas'],
    metricaImpactante: '0 rechazos DIAN con validación previa',
    caracteristicasIA: ['Validación XSD', 'Detección de errores', 'Forecast tributario'],
    emoji: '🧾',
    hashtagsEspecificos: ['#FacturaciónElectrónica', '#DIAN', '#ContabilidadColombia'],
  },
  {
    id: 'wms-logistica',
    slug: 'wms-logistica',
    path: '/demo/wms-logistica',
    titulo: 'WMS Logística',
    tagline: 'Bodega + picking + despacho optimizados con IA',
    industria: 'Logística / Distribución',
    problemaResuelve: 'Bodegas caóticas donde se pierde tiempo buscando productos',
    beneficiosClave: [
      'Picking optimizado por ruta',
      'Inventario por ubicación',
      'Despacho integrado a couriers',
      'Trazabilidad lote/serie',
    ],
    publicoObjetivo: ['Operadores logísticos', 'Fabricantes con bodega propia'],
    metricaImpactante: '-35% tiempo de picking con ruta óptima IA',
    caracteristicasIA: ['Route optimization', 'Demand forecast', 'Slotting AI'],
    emoji: '📦',
    hashtagsEspecificos: ['#WMS', '#Logística', '#SupplyChain'],
  },
  {
    id: 'pos',
    slug: 'pos',
    path: '/demo/pos',
    titulo: 'POS Punto de Venta',
    tagline: 'Caja registradora + inventario + DIAN integrados',
    industria: 'Retail físico / Restaurantes',
    problemaResuelve: 'Cajas viejas que no se conectan al inventario ni al SAT/DIAN',
    beneficiosClave: [
      'Facturación electrónica integrada',
      'Inventario sincronizado en vivo',
      'Multi-tienda + reportes',
      'Soporte offline-first',
    ],
    publicoObjetivo: ['Tiendas físicas', 'Restaurantes', 'Cadenas retail'],
    metricaImpactante: 'Apertura de caja: 5 min → 30 segundos',
    caracteristicasIA: ['Predicción de inventario', 'Detección de fraude en caja'],
    emoji: '💳',
    hashtagsEspecificos: ['#POS', '#PuntoDeVenta', '#RetailTech'],
  },
  {
    id: 'hrms',
    slug: 'hrms',
    path: '/demo/hrms',
    titulo: 'HRMS Gestión Humana',
    tagline: 'Nómina + asistencia + selección + onboarding',
    industria: 'Recursos Humanos',
    problemaResuelve: 'RRHH ahogados en Excel y formularios cuando podrían enfocarse en personas',
    beneficiosClave: [
      'Nómina con parafiscales Colombia',
      'Reloj de asistencia + biometría',
      'Selección con IA matching',
      'Portal de auto-servicio empleado',
    ],
    publicoObjetivo: ['Gerentes de RRHH', 'PyMEs', 'Empresas con +50 empleados'],
    metricaImpactante: 'Liquidación de nómina: 3 días → 2 horas',
    caracteristicasIA: ['CV parsing', 'Matching automático', 'Predicción de rotación'],
    emoji: '👥',
    hashtagsEspecificos: ['#HRMS', '#RecursosHumanos', '#NóminaColombia'],
  },
  {
    id: 'automatizacion',
    slug: 'automatizacion',
    path: '/demo/automatizacion',
    titulo: 'Automatización (n8n-style)',
    tagline: 'Conecta apps + workflows visuales + ejecución automática',
    industria: 'Operaciones / Integración',
    problemaResuelve: 'Procesos manuales repetitivos que se podrían automatizar pero requieren código',
    beneficiosClave: [
      'Editor visual de workflows',
      'Conectores a Gmail, Slack, Notion, Sheets',
      'Triggers por evento / horario',
      'Manejo de errores y reintentos',
    ],
    publicoObjetivo: ['Ops', 'Marketing', 'Cualquier área con tareas repetitivas'],
    metricaImpactante: '20 horas/semana ahorradas automatizando 5 flujos',
    caracteristicasIA: ['Detección de patrones', 'Sugerencia de workflows'],
    emoji: '⚡',
    hashtagsEspecificos: ['#Automatización', '#NoCode', '#Workflows', '#n8n'],
  },
  {
    id: 'saas-boilerplate',
    slug: 'saas-boilerplate',
    path: '/demo/saas-boilerplate',
    titulo: 'SaaS Boilerplate Multi-tenant',
    tagline: 'Auth + billing + tenancy + admin listos para vender',
    industria: 'Founders / Startups SaaS',
    problemaResuelve: 'Founders pierden 3 meses construyendo lo mismo: login, billing, admin',
    beneficiosClave: [
      'Auth + roles + permisos',
      'Stripe / Wompi integrado',
      'Multi-tenancy con aislamiento',
      'Panel admin + analytics',
    ],
    publicoObjetivo: ['Founders', 'Startups', 'Equipos lanzando MVP'],
    metricaImpactante: 'De idea a SaaS funcional: 3 meses → 1 semana',
    caracteristicasIA: ['Onboarding IA', 'Pricing recommender'],
    emoji: '🚀',
    hashtagsEspecificos: ['#SaaS', '#Boilerplate', '#StartupTools', '#MultiTenant'],
  },
  {
    id: 'voice-ai',
    slug: 'voice-ai',
    path: '/demo/voice-ai',
    titulo: 'Voice AI Agent',
    tagline: 'Agente telefónico que entiende y responde como humano',
    industria: 'Call centers / Atención telefónica',
    problemaResuelve: 'Call centers caros que solo escalan contratando más personas',
    beneficiosClave: [
      'Voz natural en español',
      'Reconocimiento de intent',
      'Transferencia a humano cuando hace falta',
      'Grabación y análisis post-llamada',
    ],
    publicoObjetivo: ['Cobranza', 'Atención al cliente', 'Encuestas', 'Citas'],
    metricaImpactante: '1.000 llamadas/día con 1 agente IA',
    caracteristicasIA: ['ASR', 'TTS natural', 'NLU intents', 'Sentiment'],
    emoji: '📞',
    hashtagsEspecificos: ['#VoiceAI', '#CallCenter', '#ConversationalAI'],
  },
  {
    id: 'firma-electronica',
    slug: 'firma-electronica',
    path: '/demo/firma-electronica',
    titulo: 'Firma Electrónica Certificada',
    tagline: 'Firma documentos legalmente válidos en segundos',
    industria: 'Legal / Contratos / Notarial',
    problemaResuelve: 'Contratos que tardan semanas en firmarse por todos los stakeholders',
    beneficiosClave: [
      'Firma con validez jurídica (Ley 527)',
      'Workflow multi-firmante',
      'Audit trail completo',
      'API para integrar a tu producto',
    ],
    publicoObjetivo: ['Bufetes', 'RRHH', 'Inmobiliarias', 'Banca'],
    metricaImpactante: 'Cierre de contrato: 2 semanas → 1 hora',
    caracteristicasIA: ['Detección de campos', 'Verificación de identidad'],
    emoji: '✒️',
    hashtagsEspecificos: ['#FirmaElectrónica', '#eSignature', '#LegalTech'],
  },
  {
    id: 'scraping',
    slug: 'scraping',
    path: '/demo/scraping',
    titulo: 'Web Scraping & Monitoring',
    tagline: 'Extrae datos de cualquier sitio + alertas en tiempo real',
    industria: 'Inteligencia competitiva / Ecommerce / Real estate',
    problemaResuelve: 'Empresas que no saben qué hace la competencia hasta que es tarde',
    beneficiosClave: [
      'Scraping resistente a bloqueos',
      'Monitoreo de precios / disponibilidad',
      'Datos estructurados listos para BI',
      'Alertas Slack / email',
    ],
    publicoObjetivo: ['Pricing teams', 'Market research', 'Inmobiliarias'],
    metricaImpactante: 'Monitor 10.000 SKUs competencia con 1 setup',
    caracteristicasIA: ['Extracción semántica', 'Anti-bloqueo IA', 'Cambio detection'],
    emoji: '🕷️',
    hashtagsEspecificos: ['#WebScraping', '#DataExtraction', '#CompetitiveIntel'],
  },
  {
    id: 'code-review-ia',
    slug: 'code-review-ia',
    path: '/demo/code-review-ia',
    titulo: 'Code Review con IA',
    tagline: 'PR analizado en segundos: bugs, seguridad, estilo',
    industria: 'Software development',
    problemaResuelve: 'PRs estancados días esperando review de un senior ocupado',
    beneficiosClave: [
      'Detección de bugs + vulnerabilidades',
      'Sugerencias de refactor',
      'Compliance con guías de estilo',
      'Integración GitHub / GitLab',
    ],
    publicoObjetivo: ['CTOs', 'Tech leads', 'Equipos de dev'],
    metricaImpactante: 'Review time: 4 horas → 5 minutos',
    caracteristicasIA: ['Bug detection', 'Security scan', 'Refactor suggest'],
    emoji: '💻',
    hashtagsEspecificos: ['#CodeReview', '#DevOps', '#DeveloperTools'],
  },
  {
    id: 'moderacion-contenido',
    slug: 'moderacion-contenido',
    path: '/demo/moderacion-contenido',
    titulo: 'Moderación de Contenido IA',
    tagline: 'Detecta toxicidad, spam, abuso en segundos',
    industria: 'Plataformas / Marketplaces / Social',
    problemaResuelve: 'Plataformas user-generated con contenido tóxico que daña la marca',
    beneficiosClave: [
      'Detección de toxicidad multi-idioma',
      'Filtrado de imágenes inapropiadas',
      'Cola de revisión humana',
      'Reportes de compliance',
    ],
    publicoObjetivo: ['Marketplaces', 'Foros', 'Apps sociales', 'Edtech'],
    metricaImpactante: '99.2% precisión detectando hate speech',
    caracteristicasIA: ['Text toxicity', 'Image NSFW', 'Multi-lingual'],
    emoji: '🛡️',
    hashtagsEspecificos: ['#ContentModeration', '#TrustAndSafety', '#AIEthics'],
  },
  {
    id: 'delivery',
    slug: 'delivery',
    path: '/demo/delivery',
    titulo: 'Delivery & Last Mile',
    tagline: 'Rutas óptimas + tracking + app de repartidor',
    industria: 'Logística última milla',
    problemaResuelve: 'Empresas de delivery con repartidores ineficientes y clientes sin tracking',
    beneficiosClave: [
      'Optimización de rutas multi-paquete',
      'App nativa repartidor + cliente',
      'Tracking en tiempo real',
      'Prueba de entrega digital',
    ],
    publicoObjetivo: ['Empresas de delivery', 'Ecommerce con flota propia', 'Restaurantes'],
    metricaImpactante: '+25% paquetes/repartidor con ruta IA',
    caracteristicasIA: ['Route optimization', 'ETA prediction', 'Demand forecast'],
    emoji: '🛵',
    hashtagsEspecificos: ['#Delivery', '#LastMile', '#LogísticaUrbana'],
  },
  {
    id: 'loyalty',
    slug: 'loyalty',
    path: '/demo/loyalty',
    titulo: 'Programa de Fidelización',
    tagline: 'Puntos + niveles + recompensas personalizadas',
    industria: 'Retail / Restaurantes / Servicios',
    problemaResuelve: 'Programas de fidelización aburridos donde nadie redime puntos',
    beneficiosClave: [
      'Puntos + niveles configurables',
      'Catálogo de recompensas',
      'Segmentación + ofertas IA',
      'App para el cliente final',
    ],
    publicoObjetivo: ['Retailers', 'Restaurantes', 'Aerolíneas', 'Hoteles'],
    metricaImpactante: '+38% retención con recompensas personalizadas',
    caracteristicasIA: ['Reward recommender', 'Churn prediction', 'Segmentation'],
    emoji: '⭐',
    hashtagsEspecificos: ['#Loyalty', '#CustomerRetention', '#CRMRetail'],
  },
];

export const HASHTAGS_GLOBALES = [
  '#Koptup',
  '#SoftwareAMedida',
  '#TransformaciónDigital',
  '#TechLatam',
  '#IAGenerativa',
  '#DesarrolloWeb',
  '#Colombia',
  '#Innovación',
  '#SaaS',
  '#Productividad',
];

export const ANGULOS_LABELS: Record<AnguloPost, { label: string; emoji: string; descripcion: string }> = {
  lanzamiento: {
    label: 'Lanzamiento',
    emoji: '🚀',
    descripcion: 'Anuncio de nueva funcionalidad o demo recién publicada',
  },
  'caso-uso': {
    label: 'Caso de uso',
    emoji: '🎯',
    descripcion: 'Ejemplo concreto: una clínica/ecommerce/bufete usándolo',
  },
  educativo: {
    label: 'Educativo',
    emoji: '🧠',
    descripcion: 'Explica un concepto (RAG, OCR, multi-tenant) con la demo como ejemplo',
  },
  testimonio: {
    label: 'Testimonio',
    emoji: '💬',
    descripcion: 'Cita de cliente o reflexión personal sobre el resultado',
  },
  'detras-camaras': {
    label: 'Detrás de cámaras',
    emoji: '🛠️',
    descripcion: 'Cómo se construyó, stack tecnológico, decisiones de diseño',
  },
  comparativa: {
    label: 'Comparativa',
    emoji: '⚖️',
    descripcion: 'Antes vs después / nuestra solución vs alternativa común',
  },
  'tip-rapido': {
    label: 'Tip rápido',
    emoji: '💡',
    descripcion: 'Un único consejo accionable que el lector puede aplicar hoy',
  },
  'pregunta-engagement': {
    label: 'Pregunta engagement',
    emoji: '❓',
    descripcion: 'Pregunta abierta para provocar comentarios y debate',
  },
};

export const TONOS_LABELS: Record<TonoPost, { label: string; descripcion: string }> = {
  profesional: { label: 'Profesional', descripcion: 'Formal, datos, métricas duras' },
  cercano: { label: 'Cercano', descripcion: 'Conversacional, emojis, primera persona' },
  tecnico: { label: 'Técnico', descripcion: 'Stack, arquitectura, jerga developer' },
  storytelling: { label: 'Storytelling', descripcion: 'Cuenta una historia con principio/medio/fin' },
  controversial: { label: 'Controversial', descripcion: 'Opinión fuerte que provoca debate' },
};

export interface DiaCalendario {
  dia: number;
  demoId: string;
  angulo: AnguloPost;
  tipoContenido: TipoContenido;
  notaEstrategica: string;
}

/**
 * Plan editorial 30 días. Cubre los 26 demos con variedad de ángulos
 * y mezcla formatos (texto / carrusel / imagen / video).
 * Lunes a viernes: contenido fuerte. Sábado/domingo: pregunta o tip ligero.
 */
export const CALENDARIO_30_DIAS: DiaCalendario[] = [
  { dia: 1, demoId: 'chatbot', angulo: 'lanzamiento', tipoContenido: 'video', notaEstrategica: 'Abrir el mes con el demo flagship en video corto (15s)' },
  { dia: 2, demoId: 'ecommerce', angulo: 'caso-uso', tipoContenido: 'carrusel', notaEstrategica: 'Carrusel 5 slides: problema → solución → métricas' },
  { dia: 3, demoId: 'dashboard-ejecutivo', angulo: 'comparativa', tipoContenido: 'imagen', notaEstrategica: 'Antes/después: reporte estático vs dashboard IA' },
  { dia: 4, demoId: 'gestor-documentos', angulo: 'educativo', tipoContenido: 'texto', notaEstrategica: 'Explicar qué es OCR + clause extraction' },
  { dia: 5, demoId: 'crm-ia', angulo: 'tip-rapido', tipoContenido: 'texto', notaEstrategica: 'Un único tip de lead scoring que cualquiera puede aplicar' },
  { dia: 6, demoId: 'sistema-reservas', angulo: 'pregunta-engagement', tipoContenido: 'texto', notaEstrategica: 'Sábado ligero: pregunta sobre no-shows' },
  { dia: 7, demoId: 'helpdesk-ia', angulo: 'caso-uso', tipoContenido: 'texto', notaEstrategica: 'Domingo: historia de un equipo soporte saturado' },
  { dia: 8, demoId: 'voice-ai', angulo: 'lanzamiento', tipoContenido: 'video', notaEstrategica: 'Lunes fuerte: demo de voz en video' },
  { dia: 9, demoId: 'erp', angulo: 'detras-camaras', tipoContenido: 'carrusel', notaEstrategica: 'Cómo construimos el ERP modular' },
  { dia: 10, demoId: 'facturacion-electronica', angulo: 'tip-rapido', tipoContenido: 'imagen', notaEstrategica: 'Infografía: error común que rechaza la DIAN' },
  { dia: 11, demoId: 'control-proyectos', angulo: 'caso-uso', tipoContenido: 'carrusel', notaEstrategica: 'PM construcción: predicción de delays' },
  { dia: 12, demoId: 'lms', angulo: 'educativo', tipoContenido: 'texto', notaEstrategica: 'Por qué adaptive learning gana sobre cursos fijos' },
  { dia: 13, demoId: 'firma-electronica', angulo: 'pregunta-engagement', tipoContenido: 'texto', notaEstrategica: 'Sábado: ¿cuánto tardás en cerrar un contrato?' },
  { dia: 14, demoId: 'telemedicina', angulo: 'caso-uso', tipoContenido: 'imagen', notaEstrategica: 'Domingo: paciente rural accediendo a especialista' },
  { dia: 15, demoId: 'automatizacion', angulo: 'lanzamiento', tipoContenido: 'video', notaEstrategica: 'Mitad de mes: video demo n8n-style' },
  { dia: 16, demoId: 'wms-logistica', angulo: 'comparativa', tipoContenido: 'imagen', notaEstrategica: 'Picking sin IA vs con IA' },
  { dia: 17, demoId: 'gestor-contenido', angulo: 'tip-rapido', tipoContenido: 'texto', notaEstrategica: 'Un prompt que cambia cómo escribís emails' },
  { dia: 18, demoId: 'pos', angulo: 'detras-camaras', tipoContenido: 'carrusel', notaEstrategica: 'POS offline-first: cómo lo logramos' },
  { dia: 19, demoId: 'hrms', angulo: 'caso-uso', tipoContenido: 'texto', notaEstrategica: 'Empresa 200 empleados liquidando nómina en 2 horas' },
  { dia: 20, demoId: 'saas-boilerplate', angulo: 'educativo', tipoContenido: 'carrusel', notaEstrategica: '5 cosas que tu MVP NO necesita construir' },
  { dia: 21, demoId: 'scraping', angulo: 'pregunta-engagement', tipoContenido: 'texto', notaEstrategica: 'Sábado: ¿cómo monitoreás competencia?' },
  { dia: 22, demoId: 'loyalty', angulo: 'caso-uso', tipoContenido: 'imagen', notaEstrategica: 'Domingo: retailer +38% retención' },
  { dia: 23, demoId: 'code-review-ia', angulo: 'tip-rapido', tipoContenido: 'texto', notaEstrategica: 'Tono controversial: "Si tu PR review tarda más de 1 día, tu proceso está roto"' },
  { dia: 24, demoId: 'moderacion-contenido', angulo: 'educativo', tipoContenido: 'texto', notaEstrategica: 'Toxicidad en marketplaces: qué medir' },
  { dia: 25, demoId: 'delivery', angulo: 'caso-uso', tipoContenido: 'video', notaEstrategica: 'Video: ruta sub-óptima vs optimizada' },
  { dia: 26, demoId: 'chatbot', angulo: 'testimonio', tipoContenido: 'imagen', notaEstrategica: 'Reflexión personal sobre lanzar el chatbot' },
  { dia: 27, demoId: 'dashboard-ejecutivo', angulo: 'tip-rapido', tipoContenido: 'texto', notaEstrategica: 'Una pregunta que todo CEO debería hacerle a su data' },
  { dia: 28, demoId: 'ecommerce', angulo: 'pregunta-engagement', tipoContenido: 'texto', notaEstrategica: 'Sábado: ¿cuál es tu mayor freno para vender online?' },
  { dia: 29, demoId: 'crm-ia', angulo: 'detras-camaras', tipoContenido: 'carrusel', notaEstrategica: 'Domingo lento: cómo decidimos el modelo de lead scoring' },
  { dia: 30, demoId: 'chatbot', angulo: 'lanzamiento', tipoContenido: 'video', notaEstrategica: 'Cerrar mes: roadmap del siguiente sprint' },
];
