/**
 * Datos de ejemplo de la demo: seis pull requests de "Billetera Andina", una
 * fintech FICTICIA (no existe; los nombres de personas, repositorios y NIT son
 * inventados). Cada PR trae sus propios archivos, comentarios de la IA
 * (pregenerados para la demo), pruebas sugeridas y actividad.
 *
 * Las vulnerabilidades de dependencias (CVE-2024-21538 en cross-spawn y
 * CVE-2024-37890 en ws) son avisos públicos reales, con sus versiones
 * corregidas reales, para que el ejemplo sea verificable.
 */
import type { PR } from './analyzer';

/** Usuaria con la que "revisas" en la demo (filtros "Míos" y "Por revisar"). */
export const DEMO_USER = 'daniela.v';
export const COMPANY = 'Billetera Andina';
export const BASE_BRANCH = 'main';

export const SAMPLE_PRS: PR[] = [
  // ---------------------------------------------------------------------------
  {
    id: 'p218',
    number: 218,
    title: {
      es: 'feat(pagos): webhook de confirmación de pagos PSE (sandbox)',
      en: 'feat(payments): PSE payment confirmation webhook (sandbox)',
    },
    summary: {
      es: 'Agrega el endpoint que recibe la confirmación de la pasarela de pagos (PSE en modo sandbox) y marca el pago como aprobado.',
      en: 'Adds the endpoint that receives the payment gateway confirmation (PSE in sandbox mode) and marks the payment as approved.',
    },
    repo: 'billetera-andina/api-pagos',
    branch: 'feat/webhook-pse',
    author: 'andres.m',
    reviewers: ['daniela.v', 'laura.g'],
    status: 'inReview',
    openedAt: '2026-10-07T16:40',
    firstReviewMin: 2,
    commits: 3,
    files: [
      {
        path: 'src/pagos/webhook.controller.ts',
        oldCode: [],
        newCode: [
          "import { Router } from 'express';",
          "import { pagosService } from './pagos.service';",
          "import { pasarela } from './pasarela.client';",
          '',
          'export const webhookRouter = Router();',
          '',
          "webhookRouter.post('/webhooks/pasarela', async (req, res) => {",
          '  const evento = req.body;',
          "  if (evento.estado === 'APROBADO') {",
          '    await pagosService.confirmar(evento.referencia, evento.valorCentavos);',
          '  }',
          '  res.sendStatus(200);',
          '});',
        ],
      },
      {
        path: 'src/pagos/pagos.service.ts',
        oldCode: [
          'export const pagosService = {',
          '  async confirmar(referencia: string, valor: number) {',
          '    const pago = await Pago.findOne({ referencia });',
          "    pago.estado = 'APROBADO';",
          '    await pago.save();',
          '  },',
          '};',
        ],
        newCode: [
          'export const pagosService = {',
          '  async confirmar(referencia: string, valorCentavos: number) {',
          '    const pago = await Pago.findOne({ referencia });',
          '    if (!pago) throw new PagoNoEncontrado(referencia);',
          '    pago.estado = EstadoPago.APROBADO;',
          '    pago.valorConfirmadoCentavos = valorCentavos;',
          '    await pago.save();',
          '  },',
          '};',
        ],
      },
    ],
    comments: [
      {
        id: 'c218-1',
        file: 'src/pagos/webhook.controller.ts',
        line: 8,
        severity: 'blocking',
        category: 'security',
        origin: 'ai-sample',
        rule: { es: 'Regla del equipo #2: todo webhook verifica la firma del emisor', en: 'Team rule #2: every webhook verifies the sender signature' },
        message: {
          es: 'El evento de la pasarela se procesa sin verificar su firma.',
          en: 'The gateway event is processed without verifying its signature.',
        },
        explanation: {
          es: 'Cualquiera que conozca la URL podría enviar un evento con estado APROBADO y marcar como pagada una orden que nadie pagó. pasarela.client ya está importado: verifica la firma con el cuerpo original de la petición antes de leer el evento.',
          en: 'Anyone who knows the URL could send an event with status APROBADO and mark an unpaid order as paid. pasarela.client is already imported: verify the signature against the raw request body before reading the event.',
        },
        fix: "  const evento = pasarela.verificarFirma(req.rawBody, req.header('x-firma-pasarela'));",
      },
      {
        id: 'c218-2',
        file: 'src/pagos/webhook.controller.ts',
        line: 10,
        severity: 'blocking',
        category: 'bug',
        origin: 'ai-sample',
        rule: { es: 'Regla del equipo #4: los webhooks son idempotentes', en: 'Team rule #4: webhooks are idempotent' },
        message: {
          es: 'Sin idempotencia: si la pasarela reintenta el webhook, el pago se confirma dos veces.',
          en: 'No idempotency: if the gateway retries the webhook, the payment is confirmed twice.',
        },
        explanation: {
          es: 'Las pasarelas reenvían el evento cuando no reciben respuesta a tiempo. Registra el idEvento con un índice único y procesa el pago solo la primera vez que llega.',
          en: 'Gateways resend the event when they do not get a timely response. Store idEvento with a unique index and process the payment only the first time it arrives.',
        },
        fix: [
          '    if (await eventosProcesados.registrar(evento.idEvento)) {',
          '      await pagosService.confirmar(evento.referencia, evento.valorCentavos);',
          '    }',
        ].join('\n'),
      },
      {
        id: 'c218-3',
        file: 'src/pagos/webhook.controller.ts',
        line: 9,
        severity: 'suggestion',
        category: 'style',
        origin: 'ai-sample',
        message: {
          es: "Compara con la constante EstadoPago.APROBADO en lugar del texto 'APROBADO'.",
          en: "Compare against the EstadoPago.APROBADO constant instead of the 'APROBADO' string.",
        },
        explanation: {
          es: 'El compilador no detecta un error de tipeo en un texto; con la constante del dominio sí. Impórtala desde ./pagos.model, como ya hace pagos.service.ts.',
          en: 'The compiler will not catch a typo in a string; it will with the domain constant. Import it from ./pagos.model, as pagos.service.ts already does.',
        },
        fix: '  if (evento.estado === EstadoPago.APROBADO) {',
      },
      {
        id: 'c218-4',
        file: 'src/pagos/pagos.service.ts',
        line: 6,
        severity: 'warning',
        category: 'bug',
        origin: 'ai-sample',
        message: {
          es: 'No se compara el valor que confirma la pasarela con el valor del pago.',
          en: 'The amount confirmed by the gateway is not compared with the payment amount.',
        },
        explanation: {
          es: 'Si la pasarela confirma un valor distinto (por ejemplo, un pago parcial), el pago queda aprobado por el total. Rechaza la confirmación y deja el pago para revisión manual.',
          en: 'If the gateway confirms a different amount (for example, a partial payment), the payment is approved for the full amount. Reject the confirmation and leave the payment for manual review.',
        },
        fix: [
          '    if (pago.valorCentavos !== valorCentavos) throw new ValorNoCoincide(referencia, valorCentavos);',
          '    pago.valorConfirmadoCentavos = valorCentavos;',
        ].join('\n'),
      },
    ],
    tests: [
      {
        id: 't218-1',
        kind: 'integration',
        file: 'test/pagos/webhook.e2e.spec.ts',
        name: { es: 'rechaza con 401 un evento con firma inválida', en: 'rejects an event with an invalid signature with 401' },
        code: [
          "it('rechaza con 401 un evento con firma inválida', async () => {",
          '  const res = await request(app)',
          "    .post('/webhooks/pasarela')",
          "    .set('x-firma-pasarela', 'firma-falsa')",
          "    .send({ idEvento: 'ev_1', referencia: 'ORD-1001', estado: 'APROBADO', valorCentavos: 12_500_000 });",
          '  expect(res.status).toBe(401);',
          "  expect(await Pago.findOne({ referencia: 'ORD-1001' })).toMatchObject({ estado: 'PENDIENTE' });",
          '});',
        ].join('\n'),
      },
      {
        id: 't218-2',
        kind: 'integration',
        file: 'test/pagos/webhook.e2e.spec.ts',
        name: { es: 'procesa una sola vez un evento reenviado', en: 'processes a resent event only once' },
        code: [
          "it('procesa una sola vez un evento reenviado', async () => {",
          "  const evento = eventoFirmado({ idEvento: 'ev_2', referencia: 'ORD-1002', valorCentavos: 8_990_000 });",
          '  await enviar(evento);',
          '  await enviar(evento);',
          '  expect(pagosService.confirmar).toHaveBeenCalledTimes(1);',
          '});',
        ].join('\n'),
      },
      {
        id: 't218-3',
        kind: 'unit',
        file: 'src/pagos/pagos.service.spec.ts',
        name: { es: 'no aprueba el pago si el valor confirmado no coincide', en: 'does not approve the payment if the confirmed amount does not match' },
        code: [
          "it('no aprueba el pago si el valor confirmado no coincide', async () => {",
          "  await crearPago({ referencia: 'ORD-1003', valorCentavos: 25_000_000 });",
          "  await expect(pagosService.confirmar('ORD-1003', 20_000_000)).rejects.toThrow(ValorNoCoincide);",
          '});',
        ].join('\n'),
      },
    ],
    events: [
      { at: '2026-10-07T16:40', kind: 'opened', who: 'andres.m' },
      { at: '2026-10-07T16:42', kind: 'aiReview', who: 'revisor-ia', detail: '4' },
    ],
  },
  // ---------------------------------------------------------------------------
  {
    id: 'p217',
    number: 217,
    title: {
      es: 'fix(facturas): redondeo del IVA del 19 % en COP',
      en: 'fix(invoices): 19% VAT rounding in COP',
    },
    summary: {
      es: 'Cambia el cálculo del IVA para trabajar con montos en centavos y evitar diferencias de un peso entre la factura y lo recaudado.',
      en: 'Changes the VAT calculation to work with amounts in cents and avoid one-peso differences between the invoice and the amount collected.',
    },
    repo: 'billetera-andina/facturacion',
    branch: 'fix/redondeo-iva',
    author: 'camila.r',
    reviewers: ['daniela.v'],
    status: 'changesRequested',
    openedAt: '2026-10-06T10:05',
    firstReviewMin: 3,
    commits: 2,
    files: [
      {
        path: 'src/facturas/calcular-iva.ts',
        oldCode: [
          'export function calcularIva(subtotal: number): number {',
          '  return subtotal * 0.19;',
          '}',
          '',
          'export function totalFactura(subtotal: number): number {',
          '  return subtotal + calcularIva(subtotal);',
          '}',
        ],
        newCode: [
          'const TARIFA_IVA = 0.19;',
          '',
          'export function calcularIva(subtotalCentavos: number): number {',
          '  return subtotalCentavos * TARIFA_IVA;',
          '}',
          '',
          'export function totalFactura(subtotalCentavos: number): number {',
          '  return subtotalCentavos + calcularIva(subtotalCentavos);',
          '}',
        ],
      },
    ],
    comments: [
      {
        id: 'c217-1',
        file: 'src/facturas/calcular-iva.ts',
        line: 4,
        severity: 'blocking',
        category: 'bug',
        origin: 'ai-sample',
        rule: { es: 'Regla del equipo #1: los montos en COP son enteros en centavos', en: 'Team rule #1: COP amounts are integers in cents' },
        message: {
          es: 'El IVA puede quedar con fracciones de centavo: el 19 % de 1.999 centavos da 379,81.',
          en: 'VAT can end up with fractions of a cent: 19% of 1,999 cents is 379.81.',
        },
        explanation: {
          es: 'Multiplicar por 0.19 en punto flotante deja decimales que luego cada sistema redondea distinto. Multiplica por la tarifa entera y redondea una sola vez: el IVA siempre será un número entero de centavos.',
          en: 'Multiplying by 0.19 in floating point leaves decimals that each system later rounds differently. Multiply by the integer rate and round once: VAT will always be a whole number of cents.',
        },
        fix: '  return Math.round((subtotalCentavos * 19) / 100);',
      },
      {
        id: 'c217-2',
        file: 'src/facturas/calcular-iva.ts',
        line: 1,
        severity: 'info',
        category: 'style',
        origin: 'ai-sample',
        message: { es: 'La tarifa queda fija en el código.', en: 'The rate is hard-coded.' },
        explanation: {
          es: 'Si facturas productos exentos o con tarifa del 5 %, recibe la tarifa como parámetro o léela del catálogo de productos.',
          en: 'If you invoice exempt products or products at the 5% rate, take the rate as a parameter or read it from the product catalog.',
        },
      },
      {
        id: 'c217-3',
        file: 'src/facturas/calcular-iva.ts',
        line: 8,
        severity: 'warning',
        category: 'tests',
        origin: 'ai-sample',
        message: {
          es: 'Faltan pruebas con valores límite (0, un centavo y medio centavo).',
          en: 'Missing tests with edge values (0, one cent and half a cent).',
        },
        explanation: {
          es: 'El cambio de redondeo es justo donde aparecen los errores. En la pestaña Pruebas sugeridas hay tres casos listos para agregar al PR; al agregar uno, este comentario se da por resuelto.',
          en: 'The rounding change is exactly where bugs show up. The Suggested tests tab has three cases ready to add to the PR; adding one resolves this comment.',
        },
      },
    ],
    tests: [
      {
        id: 't217-1',
        kind: 'unit',
        file: 'src/facturas/calcular-iva.spec.ts',
        name: { es: 'calcula el IVA de $1.999,00 sin fracciones de centavo', en: 'computes VAT on $1,999.00 with no fractions of a cent' },
        code: [
          "it('calcula el IVA de $1.999,00 sin fracciones de centavo', () => {",
          '  expect(calcularIva(199_900)).toBe(37_981);',
          '});',
        ].join('\n'),
      },
      {
        id: 't217-2',
        kind: 'unit',
        file: 'src/facturas/calcular-iva.spec.ts',
        name: { es: 'redondea medio centavo hacia arriba', en: 'rounds half a cent up' },
        code: [
          "it('redondea medio centavo hacia arriba', () => {",
          '  expect(calcularIva(1_050)).toBe(200); // 199,5 → 200',
          '});',
        ].join('\n'),
      },
      {
        id: 't217-3',
        kind: 'unit',
        file: 'src/facturas/calcular-iva.spec.ts',
        name: { es: 'un subtotal de 0 no genera IVA', en: 'a subtotal of 0 produces no VAT' },
        code: [
          "it('un subtotal de 0 no genera IVA', () => {",
          '  expect(calcularIva(0)).toBe(0);',
          '  expect(totalFactura(0)).toBe(0);',
          '});',
        ].join('\n'),
      },
    ],
    events: [
      { at: '2026-10-06T10:05', kind: 'opened', who: 'camila.r' },
      { at: '2026-10-06T10:08', kind: 'aiReview', who: 'revisor-ia', detail: '3' },
      { at: '2026-10-06T11:20', kind: 'changesRequested', who: 'daniela.v' },
    ],
  },
  // ---------------------------------------------------------------------------
  {
    id: 'p216',
    number: 216,
    title: {
      es: 'feat(kyc): validación de cédula y NIT en el registro',
      en: 'feat(kyc): ID number and NIT validation at sign-up',
    },
    summary: {
      es: 'Valida el NIT (con su dígito de verificación) y los datos de la cédula cuando un cliente se registra, antes de crearlo.',
      en: 'Validates the NIT (Colombian tax ID, with its check digit) and the ID number data when a customer signs up, before creating it.',
    },
    repo: 'billetera-andina/api-clientes',
    branch: 'feat/kyc-validaciones',
    author: 'julian.p',
    reviewers: ['daniela.v'],
    status: 'open',
    openedAt: '2026-10-08T08:20',
    firstReviewMin: 2,
    commits: 4,
    files: [
      {
        path: 'src/kyc/validar-nit.ts',
        oldCode: [],
        newCode: [
          'const PESOS = [3, 7, 13, 17, 19, 23, 29, 37, 41, 43, 47, 53, 59, 67, 71];',
          '',
          'export function digitoVerificacion(nit: string): number {',
          "  const digitos = nit.replace(/\\D/g, '').split('').map(Number);",
          '  const suma = digitos.reduce((acc, d, i) => acc + d * PESOS[i], 0);',
          '  const residuo = suma % 11;',
          '  return residuo > 1 ? 11 - residuo : residuo;',
          '}',
          '',
          'export function nitValido(nitConDv: string): boolean {',
          "  const [nit, dv] = nitConDv.split('-');",
          '  return digitoVerificacion(nit) === Number(dv);',
          '}',
        ],
      },
      {
        path: 'src/kyc/registro.controller.ts',
        oldCode: [
          'export async function registrarCliente(req: Request, res: Response) {',
          '  const cliente = await clientesService.crear(req.body);',
          '  res.status(201).json(cliente);',
          '}',
        ],
        newCode: [
          'export async function registrarCliente(req: Request, res: Response) {',
          '  const { cedula, nombre, nit } = req.body;',
          '  logger.info(`Registro KYC cédula=${cedula} nombre=${nombre}`);',
          "  if (nit && !nitValido(nit)) return res.status(422).json({ error: 'NIT inválido' });",
          '  const cliente = await clientesService.crear({ cedula, nombre, nit });',
          '  res.status(201).json(cliente);',
          '}',
        ],
      },
    ],
    comments: [
      {
        id: 'c216-1',
        file: 'src/kyc/validar-nit.ts',
        line: 4,
        severity: 'blocking',
        category: 'bug',
        origin: 'ai-sample',
        message: {
          es: 'Los pesos se aplican de izquierda a derecha; el dígito de verificación los aplica desde el último dígito.',
          en: 'The weights are applied left to right; the check digit applies them from the last digit.',
        },
        explanation: {
          es: 'Con el NIT de ejemplo 900.123.456 esta función devuelve 6 y el dígito correcto es 8: rechazaría NIT válidos y aceptaría otros mal escritos. Invierte los dígitos antes de multiplicar.',
          en: 'With the sample NIT 900.123.456 this function returns 6 and the correct digit is 8: it would reject valid NITs and accept mistyped ones. Reverse the digits before multiplying.',
        },
        fix: "  const digitos = nit.replace(/\\D/g, '').split('').reverse().map(Number);",
      },
      {
        id: 'c216-2',
        file: 'src/kyc/validar-nit.ts',
        line: 11,
        severity: 'suggestion',
        category: 'bug',
        origin: 'ai-sample',
        message: {
          es: 'Si el NIT llega sin guion, dv queda undefined y Number(undefined) es NaN.',
          en: 'If the NIT arrives without a hyphen, dv is undefined and Number(undefined) is NaN.',
        },
        explanation: {
          es: 'La función devolvería false sin decir por qué. Exige el formato con guion o separa el último dígito cuando no venga.',
          en: 'The function would return false without saying why. Require the hyphenated format or split off the last digit when it is missing.',
        },
        fix: "  const [nit, dv] = nitConDv.includes('-') ? nitConDv.split('-') : [nitConDv.slice(0, -1), nitConDv.slice(-1)];",
      },
      {
        id: 'c216-3',
        file: 'src/kyc/registro.controller.ts',
        line: 3,
        severity: 'warning',
        category: 'privacy',
        origin: 'ai-sample',
        rule: { es: 'Regla del equipo #3: no se escriben datos personales en los logs (Ley 1581 de 2012)', en: 'Team rule #3: no personal data in logs (Colombian Law 1581 of 2012)' },
        message: {
          es: 'Se escriben la cédula y el nombre del cliente en los logs.',
          en: "The customer's ID number and name are written to the logs.",
        },
        explanation: {
          es: 'Son datos personales: quedan copiados en el sistema de logs, con otros permisos y otro tiempo de retención. Registra solo una referencia que no identifique a la persona.',
          en: 'They are personal data: they get copied into the logging system, with different permissions and retention. Log only a reference that does not identify the person.',
        },
        fix: "  logger.info('Registro KYC recibido', { ref: referenciaAnonima(cedula) });",
      },
      {
        id: 'c216-4',
        file: 'src/kyc/registro.controller.ts',
        line: 2,
        severity: 'suggestion',
        category: 'bug',
        origin: 'ai-sample',
        message: {
          es: 'La cédula no se valida: llega cualquier texto desde el formulario.',
          en: 'The ID number is not validated: any text from the form gets through.',
        },
        explanation: {
          es: 'Valida el cuerpo con un esquema (solo dígitos, entre 6 y 10) antes de usarlo, como ya haces con el NIT.',
          en: 'Validate the body with a schema (digits only, 6 to 10 long) before using it, as you already do with the NIT.',
        },
        fix: '  const { cedula, nombre, nit } = registroSchema.parse(req.body);',
      },
    ],
    tests: [
      {
        id: 't216-1',
        kind: 'unit',
        file: 'src/kyc/validar-nit.spec.ts',
        name: { es: 'calcula el DV 8 para el NIT de ejemplo 900123456', en: 'computes check digit 8 for the sample NIT 900123456' },
        code: [
          "it('calcula el DV 8 para el NIT de ejemplo 900123456', () => {",
          "  expect(digitoVerificacion('900123456')).toBe(8);",
          '});',
        ].join('\n'),
      },
      {
        id: 't216-2',
        kind: 'unit',
        file: 'src/kyc/validar-nit.spec.ts',
        name: { es: 'acepta el NIT con puntos y guion', en: 'accepts the NIT with dots and hyphen' },
        code: [
          "it('acepta el NIT con puntos y guion', () => {",
          "  expect(nitValido('900.123.456-8')).toBe(true);",
          '});',
        ].join('\n'),
      },
      {
        id: 't216-3',
        kind: 'integration',
        file: 'test/kyc/registro.e2e.spec.ts',
        name: { es: 'no escribe la cédula en los logs', en: 'does not write the ID number to the logs' },
        code: [
          "it('no escribe la cédula en los logs', async () => {",
          '  const logs = capturarLogs();',
          "  await request(app).post('/clientes').send({ cedula: '1012345678', nombre: 'Cliente de prueba' });",
          "  expect(logs.texto()).not.toContain('1012345678');",
          '});',
        ].join('\n'),
      },
    ],
    events: [
      { at: '2026-10-08T08:20', kind: 'opened', who: 'julian.p' },
      { at: '2026-10-08T08:22', kind: 'aiReview', who: 'revisor-ia', detail: '4' },
    ],
  },
  // ---------------------------------------------------------------------------
  {
    id: 'p215',
    number: 215,
    title: {
      es: 'chore(deps): actualizar dependencias con vulnerabilidades conocidas',
      en: 'chore(deps): update dependencies with known vulnerabilities',
    },
    summary: {
      es: 'Actualiza ws y zod. El análisis de dependencias encuentra que cross-spawn sigue en una versión con una vulnerabilidad publicada.',
      en: 'Updates ws and zod. The dependency analysis finds that cross-spawn is still on a version with a published vulnerability.',
    },
    repo: 'billetera-andina/app-web',
    branch: 'chore/deps-seguridad',
    author: 'laura.g',
    reviewers: ['daniela.v'],
    status: 'inReview',
    openedAt: '2026-10-05T15:30',
    firstReviewMin: 1,
    commits: 1,
    files: [
      {
        path: 'package.json',
        oldCode: [
          '  "dependencies": {',
          '    "cross-spawn": "7.0.3",',
          '    "ws": "8.13.0",',
          '    "zod": "3.22.4"',
          '  }',
        ],
        newCode: [
          '  "dependencies": {',
          '    "cross-spawn": "7.0.3",',
          '    "ws": "8.17.1",',
          '    "zod": "3.23.8"',
          '  }',
        ],
        oldNumbers: [12, 13, 14, 15, 16],
        newNumbers: [12, 13, 14, 15, 16],
      },
    ],
    comments: [
      {
        id: 'c215-1',
        file: 'package.json',
        line: 2,
        severity: 'blocking',
        category: 'security',
        origin: 'ai-sample',
        rule: { es: 'Regla del equipo #5: no se fusionan dependencias con vulnerabilidades de severidad alta', en: 'Team rule #5: no merging dependencies with high-severity vulnerabilities' },
        message: {
          es: 'cross-spawn 7.0.3 tiene una vulnerabilidad publicada (CVE-2024-21538, severidad alta).',
          en: 'cross-spawn 7.0.3 has a published vulnerability (CVE-2024-21538, high severity).',
        },
        explanation: {
          es: 'Es una denegación de servicio por expresión regular (ReDoS). La corrección está en la versión 7.0.5, compatible con la 7.0.3.',
          en: 'It is a regular expression denial of service (ReDoS). The fix ships in version 7.0.5, compatible with 7.0.3.',
        },
        fix: '    "cross-spawn": "7.0.5",',
        tag: 'dependency',
      },
      {
        id: 'c215-2',
        file: 'package.json',
        line: 1,
        severity: 'info',
        category: 'style',
        origin: 'ai-sample',
        message: { es: 'El PR no incluye package-lock.json.', en: 'The PR does not include package-lock.json.' },
        explanation: {
          es: 'Sin el lockfile actualizado, la versión que se instala en CI puede ser distinta de la que probaste. Ejecuta npm install y agrega el archivo al PR.',
          en: 'Without the updated lockfile, the version installed in CI may differ from the one you tested. Run npm install and add the file to the PR.',
        },
      },
    ],
    tests: [],
    dependencies: [
      {
        name: 'cross-spawn',
        from: '7.0.3',
        to: '7.0.3',
        license: 'MIT',
        fixCommentId: 'c215-1',
        fixedTo: '7.0.5',
        advisory: {
          id: 'CVE-2024-21538',
          severity: 'high',
          summary: { es: 'Denegación de servicio por expresión regular (ReDoS)', en: 'Regular expression denial of service (ReDoS)' },
          fixedIn: '7.0.5',
          url: 'https://nvd.nist.gov/vuln/detail/CVE-2024-21538',
        },
      },
      {
        name: 'ws',
        from: '8.13.0',
        to: '8.17.1',
        license: 'MIT',
        advisory: {
          id: 'CVE-2024-37890',
          severity: 'high',
          summary: { es: 'Denegación de servicio con peticiones de muchos encabezados', en: 'Denial of service via requests with many headers' },
          fixedIn: '8.17.1',
          url: 'https://nvd.nist.gov/vuln/detail/CVE-2024-37890',
        },
      },
      { name: 'zod', from: '3.22.4', to: '3.23.8', license: 'MIT' },
    ],
    events: [
      { at: '2026-10-05T15:30', kind: 'opened', who: 'laura.g' },
      { at: '2026-10-05T15:31', kind: 'aiReview', who: 'revisor-ia', detail: '2' },
    ],
  },
  // ---------------------------------------------------------------------------
  {
    id: 'p214',
    number: 214,
    title: {
      es: 'perf(reportes): exportar movimientos a CSV por streaming',
      en: 'perf(reports): stream account movements to CSV',
    },
    summary: {
      es: 'Reemplaza la exportación que armaba todo el CSV en memoria por una escritura por streaming, para exportar cuentas con cientos de miles de movimientos.',
      en: 'Replaces the export that built the whole CSV in memory with a streaming write, to export accounts with hundreds of thousands of movements.',
    },
    repo: 'billetera-andina/api-pagos',
    branch: 'perf/exportar-csv-stream',
    author: 'daniela.v',
    reviewers: ['laura.g'],
    status: 'approved',
    openedAt: '2026-10-02T11:15',
    firstReviewMin: 2,
    commits: 3,
    files: [
      {
        path: 'src/reportes/exportar-movimientos.ts',
        oldCode: [
          'export async function exportarMovimientos(cuentaIds: string[]) {',
          '  const filas = [];',
          '  for (const id of cuentaIds) {',
          '    const movimientos = await Movimiento.find({ cuentaId: id });',
          '    filas.push(...movimientos.map(aFilaCsv));',
          '  }',
          "  return filas.join('\\n');",
          '}',
        ],
        newCode: [
          'export async function exportarMovimientos(cuentaIds: string[], salida: Writable) {',
          '  for (const id of cuentaIds) {',
          '    const movimientos = await Movimiento.find({ cuentaId: id });',
          "    for (const m of movimientos) salida.write(aFilaCsv(m) + '\\n');",
          '  }',
          '  salida.end();',
          '}',
        ],
      },
    ],
    comments: [
      {
        id: 'c214-1',
        file: 'src/reportes/exportar-movimientos.ts',
        line: 2,
        endLine: 5,
        severity: 'warning',
        category: 'perf',
        origin: 'ai-sample',
        message: {
          es: 'Consulta N+1: una consulta por cuenta dentro del bucle, y cada una carga todos sus movimientos en memoria.',
          en: 'N+1 query: one query per account inside the loop, and each one loads all its movements into memory.',
        },
        explanation: {
          es: 'Con 2.000 cuentas son 2.000 consultas. Haz una sola consulta con $in y recórrela con un cursor por lotes: la memoria queda constante sin importar el tamaño del reporte.',
          en: 'With 2,000 accounts that is 2,000 queries. Run a single query with $in and iterate it with a batched cursor: memory stays constant regardless of the report size.',
        },
        fix: [
          '  const cursor = Movimiento.find({ cuentaId: { $in: cuentaIds } })',
          '    .sort({ cuentaId: 1, fecha: 1 })',
          '    .cursor({ batchSize: 1000 });',
          "  for await (const m of cursor) salida.write(aFilaCsv(m) + '\\n');",
        ].join('\n'),
      },
      {
        id: 'c214-2',
        file: 'src/reportes/exportar-movimientos.ts',
        line: 6,
        severity: 'suggestion',
        category: 'bug',
        origin: 'ai-sample',
        message: {
          es: 'Si la consulta falla, el stream de salida queda abierto.',
          en: 'If the query fails, the output stream stays open.',
        },
        explanation: {
          es: 'Envuelve el recorrido en try/finally o usa stream.pipeline para cerrar la salida y propagar el error.',
          en: 'Wrap the iteration in try/finally or use stream.pipeline to close the output and propagate the error.',
        },
      },
    ],
    initialCommentStatus: { 'c214-1': 'applied' },
    tests: [
      {
        id: 't214-1',
        kind: 'unit',
        file: 'src/reportes/exportar-movimientos.spec.ts',
        name: { es: 'exporta tres cuentas con una sola consulta', en: 'exports three accounts with a single query' },
        code: [
          "it('exporta tres cuentas con una sola consulta', async () => {",
          "  const espia = jest.spyOn(Movimiento, 'find');",
          "  await exportarMovimientos(['c1', 'c2', 'c3'], new PassThrough());",
          '  expect(espia).toHaveBeenCalledTimes(1);',
          '});',
        ].join('\n'),
      },
      {
        id: 't214-2',
        kind: 'unit',
        file: 'src/reportes/exportar-movimientos.spec.ts',
        name: { es: 'cierra la salida aunque la consulta falle', en: 'closes the output even if the query fails' },
        code: [
          "it('cierra la salida aunque la consulta falle', async () => {",
          "  jest.spyOn(Movimiento, 'find').mockImplementation(() => { throw new Error('sin conexión'); });",
          '  const salida = new PassThrough();',
          "  await expect(exportarMovimientos(['c1'], salida)).rejects.toThrow('sin conexión');",
          '  expect(salida.writableEnded).toBe(true);',
          '});',
        ].join('\n'),
      },
    ],
    events: [
      { at: '2026-10-02T11:15', kind: 'opened', who: 'daniela.v' },
      { at: '2026-10-02T11:17', kind: 'aiReview', who: 'revisor-ia', detail: '2' },
      { at: '2026-10-02T14:30', kind: 'applied', who: 'daniela.v', detail: 'src/reportes/exportar-movimientos.ts:2' },
      { at: '2026-10-03T09:40', kind: 'approved', who: 'laura.g' },
    ],
  },
  // ---------------------------------------------------------------------------
  {
    id: 'p213',
    number: 213,
    title: {
      es: 'chore(revisor): reglas del equipo para la revisión automática',
      en: 'chore(reviewer): team rules for the automated review',
    },
    summary: {
      es: 'Agrega el archivo de configuración del revisor con las cinco reglas del equipo que cita la IA en sus comentarios.',
      en: 'Adds the reviewer configuration file with the five team rules the AI cites in its comments.',
    },
    repo: 'billetera-andina/api-pagos',
    branch: 'chore/reglas-revisor',
    author: 'laura.g',
    reviewers: ['daniela.v'],
    status: 'merged',
    openedAt: '2026-10-01T09:10',
    firstReviewMin: 1,
    commits: 1,
    files: [
      {
        path: '.revisor-ia.yml',
        oldCode: [],
        newCode: [
          'idioma: es',
          'severidad_minima: sugerencia',
          'ignorar:',
          '  - "**/*.snap"',
          '  - "migraciones/**"',
          'reglas:',
          '  - id: 1',
          '    texto: "Los montos en COP se manejan como enteros en centavos."',
          '  - id: 2',
          '    texto: "Todo webhook verifica la firma del emisor antes de procesar el evento."',
          '  - id: 3',
          '    texto: "No escribas datos personales en los logs (Ley 1581 de 2012)."',
          '  - id: 4',
          '    texto: "Los webhooks son idempotentes: un evento repetido no se procesa dos veces."',
          '  - id: 5',
          '    texto: "No se fusionan dependencias con vulnerabilidades de severidad alta."',
        ],
      },
    ],
    comments: [],
    tests: [],
    events: [
      { at: '2026-10-01T09:10', kind: 'opened', who: 'laura.g' },
      { at: '2026-10-01T09:11', kind: 'aiReview', who: 'revisor-ia', detail: '0' },
      { at: '2026-10-01T11:02', kind: 'approved', who: 'daniela.v' },
      { at: '2026-10-01T15:45', kind: 'merged', who: 'laura.g' },
    ],
  },
];

/** Diff de ejemplo para "Prueba con tu diff" (tiene hallazgos de varias reglas). */
export const SAMPLE_DIFF = [
  'diff --git a/src/clientes/notificar.ts b/src/clientes/notificar.ts',
  '--- a/src/clientes/notificar.ts',
  '+++ b/src/clientes/notificar.ts',
  '@@ -1,5 +1,14 @@',
  " import axios from 'axios';",
  "+import jwt from 'jsonwebtoken';",
  ' ',
  '-export async function notificar(cliente) {',
  '-  await axios.post(URL_NOTIFICACIONES, { id: cliente.id });',
  "+const API_KEY = 'demo_clave_0000000000000000';",
  '+',
  '+export async function notificar(cliente: any, token: string) {',
  '+  const sesion = jwt.verify(token, process.env.JWT_SECRET);',
  "+  console.log('Notificando a', cliente.email, cliente.cedula);",
  '+  const total = parseFloat(cliente.saldo) * 1.19;',
  "+  if (cliente.tipo == 'empresa') {",
  "+    await axios.post('http://notificaciones.interno/enviar', { id: cliente.id, total }, { headers: { 'x-api-key': API_KEY } });",
  '+  }',
  '+  return sesion;',
  ' }',
].join('\n');
